/**
 * Per-state facts used by the state license-plate pages to differentiate
 * content. Every field here is a publicly-verifiable fact (state capital,
 * nickname, largest city by population, state AG consumer protection URL,
 * NMVTIS/title-brand handling notes). The goal is to give each state page
 * meaningfully unique editorial content rather than 51 near-identical pages.
 *
 * Sources kept stable: state.gov pages, Census Bureau city population
 * rankings, each state's Attorney General office homepage.
 */
export interface StateProfile {
  slug: string;
  nickname: string;
  capital: string;
  largestCity: string;
  /** State Attorney General consumer-protection landing page. */
  agConsumerUrl: string;
  /**
   * Short verb phrase about the state's salvage-title threshold or
   * brand-handling quirk. Kept generic where rules vary year to year.
   */
  titleBrandNote: string;
  /** Whether the state requires a VIN inspection for out-of-state titles. */
  vinInspectionRequired: boolean;
}

export const STATE_PROFILES: Record<string, StateProfile> = {
  alabama: {
    slug: "alabama",
    nickname: "the Yellowhammer State",
    capital: "Montgomery",
    largestCity: "Huntsville",
    agConsumerUrl: "https://www.alabamaag.gov/consumer-protection/",
    titleBrandNote: "Alabama issues salvage titles when an insurer declares a vehicle a total loss and rebuilt titles after inspection.",
    vinInspectionRequired: true,
  },
  alaska: {
    slug: "alaska",
    nickname: "the Last Frontier",
    capital: "Juneau",
    largestCity: "Anchorage",
    agConsumerUrl: "https://law.alaska.gov/department/civil/consumer/cpindex.html",
    titleBrandNote: "Alaska brands titles as salvage when damage exceeds the insurer's repair-versus-replace threshold; reconstructed titles require AS 28.10 inspection.",
    vinInspectionRequired: true,
  },
  arizona: {
    slug: "arizona",
    nickname: "the Grand Canyon State",
    capital: "Phoenix",
    largestCity: "Phoenix",
    agConsumerUrl: "https://www.azag.gov/consumer",
    titleBrandNote: "Arizona requires a Level I VIN inspection by an MVD-authorized inspector for any salvage or out-of-state title transfer.",
    vinInspectionRequired: true,
  },
  arkansas: {
    slug: "arkansas",
    nickname: "the Natural State",
    capital: "Little Rock",
    largestCity: "Little Rock",
    agConsumerUrl: "https://arkansasag.gov/consumer-protection/",
    titleBrandNote: "Arkansas issues salvage titles when damage reaches 70% of the vehicle's pre-loss value.",
    vinInspectionRequired: true,
  },
  california: {
    slug: "california",
    nickname: "the Golden State",
    capital: "Sacramento",
    largestCity: "Los Angeles",
    agConsumerUrl: "https://oag.ca.gov/consumers",
    titleBrandNote: "California marks salvage on the title when total-loss settlement is paid and requires a CHP VIN verification (REG 31) before retitling.",
    vinInspectionRequired: true,
  },
  colorado: {
    slug: "colorado",
    nickname: "the Centennial State",
    capital: "Denver",
    largestCity: "Denver",
    agConsumerUrl: "https://coag.gov/office-sections/consumer-protection/",
    titleBrandNote: "Colorado brands titles salvage at 100% of value damage and requires a peace-officer VIN verification (DR 2698) for out-of-state vehicles.",
    vinInspectionRequired: true,
  },
  connecticut: {
    slug: "connecticut",
    nickname: "the Constitution State",
    capital: "Hartford",
    largestCity: "Bridgeport",
    agConsumerUrl: "https://portal.ct.gov/AG/Consumer-Issues-Section/Consumer-Issues",
    titleBrandNote: "Connecticut issues salvage titles for vehicles less than 20 model years old when damaged beyond 75% of fair market value.",
    vinInspectionRequired: true,
  },
  delaware: {
    slug: "delaware",
    nickname: "the First State",
    capital: "Dover",
    largestCity: "Wilmington",
    agConsumerUrl: "https://attorneygeneral.delaware.gov/fraud/",
    titleBrandNote: "Delaware brands titles salvage when an insurer declares a total loss; rebuilt status requires inspection at a DMV lane.",
    vinInspectionRequired: true,
  },
  "district-of-columbia": {
    slug: "district-of-columbia",
    nickname: "the District",
    capital: "Washington",
    largestCity: "Washington",
    agConsumerUrl: "https://oag.dc.gov/consumer-protection",
    titleBrandNote: "DC follows federal NMVTIS reporting; salvage and rebuilt titles are issued through the DC DMV's Inspection Station.",
    vinInspectionRequired: true,
  },
  florida: {
    slug: "florida",
    nickname: "the Sunshine State",
    capital: "Tallahassee",
    largestCity: "Jacksonville",
    agConsumerUrl: "https://myfloridalegal.com/consumer-protection",
    titleBrandNote: "Florida brands titles certificate-of-destruction (unrebuildable), salvage, or rebuilt; FLHSMV publishes a public Motorist Modernization VIN portal.",
    vinInspectionRequired: false,
  },
  georgia: {
    slug: "georgia",
    nickname: "the Peach State",
    capital: "Atlanta",
    largestCity: "Atlanta",
    agConsumerUrl: "https://consumer.georgia.gov/",
    titleBrandNote: "Georgia issues salvage titles when repair cost reaches 75% of the vehicle's fair market value and rebuilt titles after a Department of Revenue inspection.",
    vinInspectionRequired: true,
  },
  hawaii: {
    slug: "hawaii",
    nickname: "the Aloha State",
    capital: "Honolulu",
    largestCity: "Honolulu",
    agConsumerUrl: "https://cca.hawaii.gov/ocp/",
    titleBrandNote: "Hawaii vehicle titles are administered by each county; salvage is branded when an insurer pays a total-loss settlement under HRS 286.",
    vinInspectionRequired: true,
  },
  idaho: {
    slug: "idaho",
    nickname: "the Gem State",
    capital: "Boise",
    largestCity: "Boise",
    agConsumerUrl: "https://www.ag.idaho.gov/consumer-protection/",
    titleBrandNote: "Idaho brands titles salvage when damage reaches the cost of repair plus salvage value, and requires a sheriff's VIN inspection for out-of-state titles.",
    vinInspectionRequired: true,
  },
  illinois: {
    slug: "illinois",
    nickname: "the Prairie State",
    capital: "Springfield",
    largestCity: "Chicago",
    agConsumerUrl: "https://illinoisattorneygeneral.gov/consumer-protection/",
    titleBrandNote: "Illinois issues salvage certificates when an insurer pays a total loss; a state police VIN inspection is required to retitle as rebuilt.",
    vinInspectionRequired: true,
  },
  indiana: {
    slug: "indiana",
    nickname: "the Hoosier State",
    capital: "Indianapolis",
    largestCity: "Indianapolis",
    agConsumerUrl: "https://www.in.gov/attorneygeneral/consumer-protection-division/",
    titleBrandNote: "Indiana brands titles salvage when damage reaches 70% of value and rebuilt after BMV inspection at a regional office.",
    vinInspectionRequired: true,
  },
  iowa: {
    slug: "iowa",
    nickname: "the Hawkeye State",
    capital: "Des Moines",
    largestCity: "Des Moines",
    agConsumerUrl: "https://www.iowaattorneygeneral.gov/for-consumers",
    titleBrandNote: "Iowa issues a salvage theft title when damage exceeds 70% of fair market value and a prior-salvage brand after the rebuilt inspection.",
    vinInspectionRequired: true,
  },
  kansas: {
    slug: "kansas",
    nickname: "the Sunflower State",
    capital: "Topeka",
    largestCity: "Wichita",
    agConsumerUrl: "https://ag.ks.gov/consumer-protection",
    titleBrandNote: "Kansas brands titles salvage at 75% damage and rebuilt after a Highway Patrol VIN inspection (MVE-1).",
    vinInspectionRequired: true,
  },
  kentucky: {
    slug: "kentucky",
    nickname: "the Bluegrass State",
    capital: "Frankfort",
    largestCity: "Louisville",
    agConsumerUrl: "https://www.ag.ky.gov/Priorities/Consumer-Protection/Pages/default.aspx",
    titleBrandNote: "Kentucky issues salvage titles when an insurer pays a total loss; rebuilt status follows a Kentucky State Police inspection.",
    vinInspectionRequired: true,
  },
  louisiana: {
    slug: "louisiana",
    nickname: "the Pelican State",
    capital: "Baton Rouge",
    largestCity: "New Orleans",
    agConsumerUrl: "https://www.ag.state.la.us/Section/ConsumerProtection",
    titleBrandNote: "Louisiana brands titles salvage at 75% damage and reconstructed after an OMV inspection; flood-vehicle disclosures are mandatory for the lifetime of the title.",
    vinInspectionRequired: true,
  },
  maine: {
    slug: "maine",
    nickname: "the Pine Tree State",
    capital: "Augusta",
    largestCity: "Portland",
    agConsumerUrl: "https://www.maine.gov/ag/consumer/",
    titleBrandNote: "Maine does not issue salvage titles below 75% damage; flood-damaged vehicles must be branded for life under 29-A MRSA.",
    vinInspectionRequired: true,
  },
  maryland: {
    slug: "maryland",
    nickname: "the Old Line State",
    capital: "Annapolis",
    largestCity: "Baltimore",
    agConsumerUrl: "https://www.marylandattorneygeneral.gov/Pages/CPD/default.aspx",
    titleBrandNote: "Maryland issues salvage titles when damage reaches 75% of fair market value and rebuilt salvage after MSP safety inspection.",
    vinInspectionRequired: true,
  },
  massachusetts: {
    slug: "massachusetts",
    nickname: "the Bay State",
    capital: "Boston",
    largestCity: "Boston",
    agConsumerUrl: "https://www.mass.gov/orgs/office-of-consumer-affairs-and-business-regulation",
    titleBrandNote: "Massachusetts brands titles salvage when the cost of repair exceeds the vehicle's pre-loss value; rebuilt status requires a state police inspection.",
    vinInspectionRequired: true,
  },
  michigan: {
    slug: "michigan",
    nickname: "the Great Lakes State",
    capital: "Lansing",
    largestCity: "Detroit",
    agConsumerUrl: "https://www.michigan.gov/ag/consumer-protection",
    titleBrandNote: "Michigan brands titles salvage at 75% damage and scrap at 91% (cannot be retitled); rebuilt status follows a state police VIN/parts inspection.",
    vinInspectionRequired: true,
  },
  minnesota: {
    slug: "minnesota",
    nickname: "the North Star State",
    capital: "Saint Paul",
    largestCity: "Minneapolis",
    agConsumerUrl: "https://www.ag.state.mn.us/Office/Complaint.asp",
    titleBrandNote: "Minnesota issues salvage titles for late-model vehicles with damage above 70% of value, and prior-salvage after inspection.",
    vinInspectionRequired: true,
  },
  mississippi: {
    slug: "mississippi",
    nickname: "the Magnolia State",
    capital: "Jackson",
    largestCity: "Jackson",
    agConsumerUrl: "https://www.ago.state.ms.us/divisions/consumer-protection/",
    titleBrandNote: "Mississippi brands titles salvage when damage reaches 75% of pre-loss value; rebuilt status requires Department of Revenue inspection.",
    vinInspectionRequired: true,
  },
  missouri: {
    slug: "missouri",
    nickname: "the Show-Me State",
    capital: "Jefferson City",
    largestCity: "Kansas City",
    agConsumerUrl: "https://ago.mo.gov/civil-division/consumer/",
    titleBrandNote: "Missouri brands titles salvage at 80% damage and junk above; rebuilt after a Highway Patrol Salvage Examination (MV-50).",
    vinInspectionRequired: true,
  },
  montana: {
    slug: "montana",
    nickname: "the Treasure State",
    capital: "Helena",
    largestCity: "Billings",
    agConsumerUrl: "https://dojmt.gov/consumer/",
    titleBrandNote: "Montana issues salvage titles when an insurer settles for total loss; rebuilt status follows a Montana Highway Patrol inspection.",
    vinInspectionRequired: true,
  },
  nebraska: {
    slug: "nebraska",
    nickname: "the Cornhusker State",
    capital: "Lincoln",
    largestCity: "Omaha",
    agConsumerUrl: "https://protectthegoodlife.nebraska.gov/",
    titleBrandNote: "Nebraska brands titles salvage at 75% damage and rebuilt salvage after a State Patrol inspection per Neb. Rev. Stat. 60-171.",
    vinInspectionRequired: true,
  },
  nevada: {
    slug: "nevada",
    nickname: "the Silver State",
    capital: "Carson City",
    largestCity: "Las Vegas",
    agConsumerUrl: "https://ag.nv.gov/Hot_Topics/Consumer/",
    titleBrandNote: "Nevada issues salvage titles when repair exceeds 65% of fair market value and rebuilt after DMV inspection at a Reconstructed Vehicle station.",
    vinInspectionRequired: true,
  },
  "new-hampshire": {
    slug: "new-hampshire",
    nickname: "the Granite State",
    capital: "Concord",
    largestCity: "Manchester",
    agConsumerUrl: "https://www.doj.nh.gov/consumer/",
    titleBrandNote: "New Hampshire does not issue salvage titles for vehicles 15 model years or older; rebuilt status follows DMV inspection for newer vehicles.",
    vinInspectionRequired: true,
  },
  "new-jersey": {
    slug: "new-jersey",
    nickname: "the Garden State",
    capital: "Trenton",
    largestCity: "Newark",
    agConsumerUrl: "https://www.njconsumeraffairs.gov/",
    titleBrandNote: "New Jersey brands titles salvage when damage equals or exceeds the cost of repair plus salvage value; rebuilt after MVC inspection.",
    vinInspectionRequired: true,
  },
  "new-mexico": {
    slug: "new-mexico",
    nickname: "the Land of Enchantment",
    capital: "Santa Fe",
    largestCity: "Albuquerque",
    agConsumerUrl: "https://www.nmag.gov/consumer-protection/",
    titleBrandNote: "New Mexico issues salvage titles at 75% damage and rebuilt status after MVD inspection at an authorized location.",
    vinInspectionRequired: true,
  },
  "new-york": {
    slug: "new-york",
    nickname: "the Empire State",
    capital: "Albany",
    largestCity: "New York City",
    agConsumerUrl: "https://ag.ny.gov/consumer-frauds",
    titleBrandNote: "New York brands titles salvage at 75% damage and requires a salvage vehicle examination (MV-899A) before issuing a rebuilt title.",
    vinInspectionRequired: true,
  },
  "north-carolina": {
    slug: "north-carolina",
    nickname: "the Tar Heel State",
    capital: "Raleigh",
    largestCity: "Charlotte",
    agConsumerUrl: "https://ncdoj.gov/protecting-consumers/",
    titleBrandNote: "North Carolina issues salvage titles when damage reaches 75% of pre-loss value and reconstructed after License & Theft Bureau inspection.",
    vinInspectionRequired: true,
  },
  "north-dakota": {
    slug: "north-dakota",
    nickname: "the Peace Garden State",
    capital: "Bismarck",
    largestCity: "Fargo",
    agConsumerUrl: "https://attorneygeneral.nd.gov/consumer-resources/",
    titleBrandNote: "North Dakota brands titles salvage at 75% damage for vehicles less than nine model years old, and rebuilt after DOT inspection.",
    vinInspectionRequired: true,
  },
  ohio: {
    slug: "ohio",
    nickname: "the Buckeye State",
    capital: "Columbus",
    largestCity: "Columbus",
    agConsumerUrl: "https://www.ohioattorneygeneral.gov/Individuals-and-Families/Consumers",
    titleBrandNote: "Ohio brands titles salvage when damage exceeds the fair-market value cost of repair; rebuilt after Highway Patrol inspection.",
    vinInspectionRequired: true,
  },
  oklahoma: {
    slug: "oklahoma",
    nickname: "the Sooner State",
    capital: "Oklahoma City",
    largestCity: "Oklahoma City",
    agConsumerUrl: "https://www.oag.ok.gov/consumer-protection-unit",
    titleBrandNote: "Oklahoma issues salvage titles at 60% damage and rebuilt salvage following inspection by Service Oklahoma.",
    vinInspectionRequired: true,
  },
  oregon: {
    slug: "oregon",
    nickname: "the Beaver State",
    capital: "Salem",
    largestCity: "Portland",
    agConsumerUrl: "https://justice.oregon.gov/consumer/",
    titleBrandNote: "Oregon brands titles wrecked, totaled, or reconstructed; salvage threshold is 80% of fair market value before damage.",
    vinInspectionRequired: true,
  },
  pennsylvania: {
    slug: "pennsylvania",
    nickname: "the Keystone State",
    capital: "Harrisburg",
    largestCity: "Philadelphia",
    agConsumerUrl: "https://www.attorneygeneral.gov/protect-yourself/consumer-protection/",
    titleBrandNote: "Pennsylvania brands titles salvage when an insurer settles for a total loss, and reconstructed after a State Police enhanced VIN verification.",
    vinInspectionRequired: true,
  },
  "rhode-island": {
    slug: "rhode-island",
    nickname: "the Ocean State",
    capital: "Providence",
    largestCity: "Providence",
    agConsumerUrl: "https://riag.ri.gov/consumer-protection",
    titleBrandNote: "Rhode Island issues salvage titles when damage reaches the cost of the vehicle's pre-loss value, with reconstructed brands after DMV inspection.",
    vinInspectionRequired: true,
  },
  "south-carolina": {
    slug: "south-carolina",
    nickname: "the Palmetto State",
    capital: "Columbia",
    largestCity: "Charleston",
    agConsumerUrl: "https://consumer.sc.gov/",
    titleBrandNote: "South Carolina brands titles salvage at 75% damage and rebuilt after a state-authorized inspection by the Department of Motor Vehicles.",
    vinInspectionRequired: true,
  },
  "south-dakota": {
    slug: "south-dakota",
    nickname: "the Mount Rushmore State",
    capital: "Pierre",
    largestCity: "Sioux Falls",
    agConsumerUrl: "https://consumer.sd.gov/",
    titleBrandNote: "South Dakota issues salvage titles for vehicles nine model years or newer with damage above the fair-market value cost of repair.",
    vinInspectionRequired: true,
  },
  tennessee: {
    slug: "tennessee",
    nickname: "the Volunteer State",
    capital: "Nashville",
    largestCity: "Nashville",
    agConsumerUrl: "https://www.tn.gov/attorneygeneral/working-for-tennessee/consumer.html",
    titleBrandNote: "Tennessee brands titles salvage when damage reaches 75% of fair market value, and rebuilt status follows a Department of Revenue inspection.",
    vinInspectionRequired: true,
  },
  texas: {
    slug: "texas",
    nickname: "the Lone Star State",
    capital: "Austin",
    largestCity: "Houston",
    agConsumerUrl: "https://www.texasattorneygeneral.gov/consumer-protection",
    titleBrandNote: "Texas brands titles salvage when an insurer pays a total loss and rebuilt salvage after a licensed rebuilder repair and TxDMV inspection.",
    vinInspectionRequired: true,
  },
  utah: {
    slug: "utah",
    nickname: "the Beehive State",
    capital: "Salt Lake City",
    largestCity: "Salt Lake City",
    agConsumerUrl: "https://www.utahconsumer.org/",
    titleBrandNote: "Utah issues salvage titles at the cost of repair plus salvage value, and a flood-damage brand for any vehicle submerged above the dashboard.",
    vinInspectionRequired: true,
  },
  vermont: {
    slug: "vermont",
    nickname: "the Green Mountain State",
    capital: "Montpelier",
    largestCity: "Burlington",
    agConsumerUrl: "https://ago.vermont.gov/cap/",
    titleBrandNote: "Vermont brands titles salvage when damage reaches the vehicle's actual cash value; rebuilt status follows a DMV inspection.",
    vinInspectionRequired: true,
  },
  virginia: {
    slug: "virginia",
    nickname: "the Old Dominion",
    capital: "Richmond",
    largestCity: "Virginia Beach",
    agConsumerUrl: "https://www.oag.state.va.us/consumer-protection",
    titleBrandNote: "Virginia issues salvage titles at 75% damage and rebuilt salvage after a state-licensed rebuilder repair and DMV inspection.",
    vinInspectionRequired: true,
  },
  washington: {
    slug: "washington",
    nickname: "the Evergreen State",
    capital: "Olympia",
    largestCity: "Seattle",
    agConsumerUrl: "https://www.atg.wa.gov/file-complaint",
    titleBrandNote: "Washington brands titles salvage when an insurer settles for a total loss and rebuilt status requires a State Patrol inspection.",
    vinInspectionRequired: true,
  },
  "west-virginia": {
    slug: "west-virginia",
    nickname: "the Mountain State",
    capital: "Charleston",
    largestCity: "Charleston",
    agConsumerUrl: "https://ago.wv.gov/consumerprotection/",
    titleBrandNote: "West Virginia issues salvage titles at 75% damage and reconstructed salvage after a State Police VIN inspection.",
    vinInspectionRequired: true,
  },
  wisconsin: {
    slug: "wisconsin",
    nickname: "the Badger State",
    capital: "Madison",
    largestCity: "Milwaukee",
    agConsumerUrl: "https://datcp.wi.gov/Pages/Programs_Services/ConsumerProtection.aspx",
    titleBrandNote: "Wisconsin brands titles salvage at 70% damage for vehicles less than seven model years old, with rebuilt status after a State Patrol inspection.",
    vinInspectionRequired: true,
  },
  wyoming: {
    slug: "wyoming",
    nickname: "the Equality State",
    capital: "Cheyenne",
    largestCity: "Cheyenne",
    agConsumerUrl: "https://ag.wyo.gov/consumer-protection",
    titleBrandNote: "Wyoming issues salvage titles when an insurer pays a total loss, and rebuilt status follows a Highway Patrol VIN inspection.",
    vinInspectionRequired: true,
  },
};

export function findStateProfile(slug: string): StateProfile | undefined {
  return STATE_PROFILES[slug];
}
