// Auto-generated from Wal33D/nhtsa-vin-decoder MIT-licensed WMI data.
// Merged from wmi-from-github.csv + wmi-from-wiki.csv + wmi-from-offline.csv,
// deduped and ASCII-filtered. Regenerate via tools/wal33d/build-wmi-ts.py.
// Source: https://github.com/Wal33D/nhtsa-vin-decoder (MIT, 2025 Wal33D).
//
// USE: fallback when neither NHTSA nor our hand-curated per-make decoders
// (toyota/nissan/honda/mitsubishi/...) recognise the WMI. Gives at least a
// make + country identification for 859 WMIs covering VW, BMW,
// Mercedes, Audi, Renault, Peugeot, Citroen, Fiat, Opel, Volvo, Land Rover,
// Skoda, Seat, and the bulk of the global vehicle population.

export const UNIVERSAL_WMI_MAP: Record<string, string> = {
  "10T": "Oshkosh",
  "11V": "Ottawa",
  "137": "AM General",
  "145": "Hyundai",
  "15G": "Gillig",
  "177": "Thomas",
  "17N": "John Deere",
  "18X": "WRV",
  "19U": "Acura",
  "1A4": "Chrysler",
  "1A8": "Chrysler",
  "1AC": "AMC",
  "1AM": "AMC",
  "1B3": "Dodge",
  "1B4": "Dodge",
  "1B6": "Dodge",
  "1B7": "Dodge",
  "1BA": "Blue Bird",
  "1BB": "Blue Bird",
  "1BD": "Blue Bird",
  "1C3": "Chrysler",
  "1C4": "Chrysler",
  "1C6": "Chrysler",
  "1C8": "Chrysler",
  "1C9": "Chance",
  "1CY": "Crane Carrier",
  "1D3": "Dodge",
  "1D4": "Dodge",
  "1D5": "Dodge",
  "1D7": "Dodge",
  "1D8": "Dodge",
  "1EC": "Fleetwood",
  "1F1": "Ford",
  "1F4": "Ford",
  "1F6": "Ford",
  "1F9": "FWD",
  "1FA": "Ford",
  "1FB": "Ford",
  "1FC": "Ford",
  "1FD": "Ford",
  "1FE": "Ford",
  "1FF": "Ford",
  "1FM": "Ford",
  "1FT": "Ford",
  "1FU": "Freightliner",
  "1FV": "Freightliner",
  "1G": "General Motors USA",
  "1G1": "Chevrolet",
  "1G2": "Pontiac",
  "1G3": "Oldsmobile",
  "1G4": "Buick",
  "1G5": "GMC",
  "1G6": "Cadillac",
  "1G8": "Chevrolet",
  "1GA": "Chevrolet",
  "1GB": "Chevrolet",
  "1GC": "Chevrolet",
  "1GD": "GMC",
  "1GE": "Cadillac",
  "1GF": "Flexible",
  "1GG": "Isuzu",
  "1GH": "GMC",
  "1GJ": "GMC",
  "1GK": "GMC",
  "1GM": "Pontiac",
  "1GN": "Chevrolet",
  "1GT": "GMC",
  "1GY": "Cadillac",
  "1H": "Honda USA",
  "1HD": "Harley-Davidson",
  "1HF": "Honda",
  "1HG": "Honda",
  "1HS": "International",
  "1HT": "International",
  "1HV": "International",
  "1J4": "Jeep",
  "1J6": "Jeep",
  "1J7": "Jeep",
  "1J8": "Jeep",
  "1JC": "AMC",
  "1JD": "AMC",
  "1JE": "Jeep",
  "1JF": "Jeep",
  "1JH": "Jeep",
  "1JM": "Jeep",
  "1JT": "AMC",
  "1L": "Lincoln USA",
  "1L1": "Lincoln",
  "1LN": "Lincoln",
  "1M1": "Mack",
  "1M2": "Mack",
  "1M3": "Mack",
  "1M4": "Mack Truck USA",
  "1M8": "MCI",
  "1M9": "Mynatt Truck & Equipment",
  "1MB": "Mercedes-Benz",
  "1ME": "Mercury",
  "1MR": "Lincoln",
  "1N": "Nissan USA",
  "1N4": "Nissan",
  "1N6": "Datsun",
  "1N9": "Neoplan",
  "1NK": "Kenworth",
  "1NP": "Peterbilt",
  "1NX": "Toyota",
  "1P3": "Plymouth",
  "1P4": "Plymouth",
  "1P7": "Plymouth",
  "1P9": "Panoz",
  "1R9": "Roadrunner Hay Squeeze USA",
  "1RF": "Roadmaster",
  "1S9": "Saleen",
  "1T8": "Thomas",
  "1TU": "TMC",
  "1V1": "Volkswagen",
  "1VW": "Volkswagen",
  "1WA": "Autostar",
  "1WB": "Autostar",
  "1WU": "White Volvo",
  "1WV": "Winnebago",
  "1XK": "Kenworth",
  "1XM": "AMC",
  "1XP": "Peterbilt",
  "1Y1": "Chevrolet",
  "1YV": "Mazda",
  "1Z3": "Mitsubishi",
  "1Z5": "Mitsubishi",
  "1Z7": "Mitsubishi",
  "1ZV": "Ford",
  "1ZW": "Mercury",
  "2A3": "Chrysler",
  "2A4": "Chrysler",
  "2A8": "Chrysler",
  "2B1": "Orion",
  "2B3": "Dodge",
  "2B4": "Dodge",
  "2B5": "Dodge",
  "2B6": "Dodge",
  "2B7": "Dodge",
  "2B8": "Dodge",
  "2BC": "AMC",
  "2BD": "Jeep",
  "2BT": "Jeep",
  "2C1": "Chevrolet",
  "2C3": "Chrysler",
  "2C4": "Chrysler",
  "2C7": "Pontiac",
  "2C8": "Chrysler",
  "2CC": "AMC",
  "2CH": "Chevrolet",
  "2CK": "Geo",
  "2CM": "AMC",
  "2CN": "Chevrolet",
  "2D3": "Dodge",
  "2D4": "Dodge",
  "2D6": "Dodge",
  "2D7": "Dodge",
  "2D8": "Dodge",
  "2E3": "Eagle",
  "2FA": "Ford",
  "2FB": "Ford",
  "2FC": "Ford",
  "2FD": "Ford",
  "2FF": "Ford",
  "2FM": "Ford",
  "2FT": "Ford",
  "2FU": "Freightliner",
  "2FV": "Freightliner",
  "2FW": "Sterling",
  "2FZ": "Sterling",
  "2G": "General Motors Canada",
  "2G0": "GMC",
  "2G1": "Chevrolet",
  "2G2": "Pontiac",
  "2G3": "Oldsmobile",
  "2G4": "Buick",
  "2G5": "GMC",
  "2G7": "Pontiac",
  "2G8": "Chevrolet",
  "2GA": "Chevrolet",
  "2GB": "Chevrolet",
  "2GC": "Chevrolet",
  "2GD": "GMC",
  "2GJ": "GMC",
  "2GK": "GMC",
  "2GM": "Pontiac",
  "2GN": "Chevrolet",
  "2GT": "GMC",
  "2GY": "Cadillac",
  "2HG": "Honda",
  "2HH": "Acura",
  "2HJ": "Honda",
  "2HK": "Honda",
  "2HM": "Hyundai",
  "2HN": "Acura",
  "2HS": "International",
  "2HT": "International",
  "2J4": "Jeep",
  "2J6": "Jeep",
  "2J7": "Jeep",
  "2LM": "Lincoln",
  "2M": "Mercury",
  "2M2": "Mack",
  "2ME": "Mercury",
  "2MH": "Mercury",
  "2MR": "Mercury",
  "2NK": "Kenworth",
  "2NP": "Peterbilt",
  "2NV": "Nova Bus",
  "2P3": "Plymouth",
  "2P4": "Plymouth",
  "2P5": "Plymouth",
  "2P9": "Prevost",
  "2PC": "Prevost",
  "2S2": "Suzuki",
  "2S3": "Suzuki",
  "2S4": "Suzuki",
  "2T": "Toyota Canada",
  "2T1": "Toyota",
  "2T2": "Lexus",
  "2T3": "Toyota",
  "2V4": "Volkswagen",
  "2V8": "Volkswagen",
  "2WK": "Western Star",
  "2WL": "Western Star",
  "2WM": "Western Star",
  "2XK": "Kenworth",
  "2XM": "Eagle",
  "2XP": "Peterbilt",
  "3A4": "Chrysler",
  "3A8": "Chrysler",
  "3AB": "Dina",
  "3AL": "Freightliner",
  "3B3": "Dodge",
  "3B4": "Dodge",
  "3B6": "Dodge",
  "3B7": "Dodge",
  "3BK": "Kenworth",
  "3BP": "Peterbilt",
  "3C3": "Chrysler",
  "3C4": "Chrysler",
  "3C8": "Chrysler",
  "3CA": "Chrysler",
  "3CE": "Volvo",
  "3CZ": "Honda",
  "3D3": "Dodge",
  "3D5": "Dodge",
  "3D6": "Dodge",
  "3D7": "Dodge",
  "3FA": "Ford",
  "3FB": "Ford",
  "3FC": "Ford",
  "3FD": "Ford",
  "3FE": "Ford",
  "3FF": "Ford",
  "3FR": "Ford",
  "3FT": "Ford",
  "3G": "General Motors Mexico",
  "3G1": "Chevrolet",
  "3G2": "Pontiac",
  "3G4": "Buick",
  "3G5": "Buick",
  "3G7": "Pontiac",
  "3G8": "Chevrolet",
  "3GA": "Chevrolet",
  "3GB": "Chevrolet",
  "3GC": "Chevrolet",
  "3GD": "GMC",
  "3GE": "Chevrolet",
  "3GG": "Cadillac",
  "3GK": "GMC",
  "3GM": "Pontiac",
  "3GN": "Chevrolet",
  "3GT": "GMC",
  "3GY": "Cadillac",
  "3H": "Honda Mexico",
  "3H1": "Honda",
  "3HA": "International",
  "3HG": "Honda",
  "3HM": "Honda",
  "3HS": "International",
  "3HT": "International",
  "3JB": "BRP Mexico (all-terrain vehicles)",
  "3LN": "Lincoln",
  "3MA": "Mercury",
  "3ME": "Mercury",
  "3MD": "Mazda",
  "3MV": "Mazda",
  "3MZ": "Mazda",
  "4MB": "Mitsubishi",
  "3N": "Nissan Mexico",
  "3N1": "Nissan",
  "3N6": "Nissan",
  "3N8": "Nissan",
  "3NK": "Kenworth",
  "3NM": "Peterbilt",
  "3P3": "Plymouth",
  "3TM": "Toyota",
  "3VW": "Volkswagen",
  "3WK": "Kenworth",
  "45V": "Utilimaster",
  "46G": "Gillig",
  "478": "Honda",
  "49H": "Sterling",
  "4A3": "Mitsubishi",
  "4A4": "Mitsubishi",
  "4B3": "Dodge",
  "4C3": "Chrysler",
  "4CD": "Oshkosh",
  "4DR": "Genesis",
  "4E3": "Eagle",
  "4F": "Mazda USA",
  "4F2": "Mazda",
  "4F4": "Mazda",
  "4G1": "Chevrolet",
  "4G2": "Pontiac",
  "4GB": "Chevrolet",
  "4GD": "GMC",
  "4GT": "Isuzu",
  "4J4": "Jeep",
  "4JG": "Mercedes-Benz",
  "4KB": "Chevrolet",
  "4KD": "GMC",
  "4KL": "Isuzu",
  "4M": "Mercury",
  "4M2": "Mercury",
  "4N1": "Nissan",
  "4N2": "Nissan",
  "4NU": "Isuzu",
  "4P3": "Plymouth",
  "4RK": "Nova Bus",
  "4S": "Subaru-Isuzu Automotive",
  "4S1": "Isuzu",
  "4S2": "Isuzu",
  "4S3": "Subaru",
  "4S4": "Subaru",
  "4S6": "Honda",
  "4S7": "Spartan",
  "4SL": "Magnum",
  "4T": "Toyota",
  "4T1": "Toyota",
  "4T3": "Toyota",
  "4T9": "Lumen Motors (zero-emission mid-engined car)",
  "4TA": "Toyota",
  "4UF": "Arctic Cat Inc.",
  "4US": "BMW",
  "4UZ": "Freightliner",
  "4V1": "Volvo",
  "4V2": "Volvo",
  "4V3": "Volvo",
  "4V4": "Volvo",
  "4V5": "Volvo",
  "4V6": "Volvo",
  "4VA": "Volvo",
  "4VG": "Volvo",
  "4VH": "Volvo",
  "4VJ": "Volvo",
  "4VK": "Volvo",
  "4VL": "Volvo",
  "4VM": "Volvo",
  "4VZ": "Spartan",
  "538": "Zero Motorcycles (USA)",
  "5AS": "GEM",
  "5B4": "Workhorse",
  "5CK": "Western Star Trucks",
  "5F": "Honda USA-Alabama",
  "5FN": "Honda",
  "5FP": "Honda",
  "5FY": "New Flyer",
  "5GA": "Buick",
  "5GR": "Hummer",
  "5GT": "Hummer",
  "5GZ": "Saturn",
  "5J6": "Honda",
  "5J8": "Acura",
  "5KB": "Honda",
  "5KJ": "Western Star Trucks",
  "5KK": "Western Star Trucks",
  "5L": "Lincoln",
  "5LM": "Lincoln",
  "5LT": "Lincoln",
  "5N1": "Nissan",
  "5N3": "Infiniti",
  "5NM": "Hyundai",
  "5NP": "Hyundai",
  "5PV": "Hino",
  "5S3": "Saab",
  "5SA": "Suzuki",
  "5SX": "Amercian LeFrance",
  "5T": "Toyota USA - trucks",
  "5T4": "Workhorse",
  "5TB": "Toyota",
  "5TD": "Toyota",
  "5TE": "Toyota",
  "5TF": "Toyota",
  "5UM": "BMW",
  "5UX": "BMW",
  "5XY": "Kia",
  "5Y2": "Pontiac",
  "5YJ": "Tesla Motors",
  "5YM": "BMW",
  "5Z6": "Suzuki",
  "6AB": "MAN",
  "6F4": "Nissan",
  "6F5": "Kenworth",
  "6FP": "Ford",
  "6G1": "General Motors",
  "6G2": "Pontiac",
  "6H8": "General Motors",
  "6MM": "Mitsubishi",
  "6MP": "Mercury",
  "6T1": "Toyota",
  "6U9": "Privately Imported car in Australia",
  "8A1": "Renault",
  "8AD": "Peugeot",
  "8AF": "Ford",
  "8AG": "Chevrolet",
  "8AJ": "Toyota",
  "8AK": "Suzuki",
  "8AP": "Fiat",
  "8AW": "Volkswagen",
  "8GD": "Peugeot",
  "8GG": "Chevrolet",
  "935": "Citroen",
  "936": "Peugeot",
  "93H": "Honda",
  "93R": "Toyota",
  "93U": "Audi",
  "93V": "Audi Brazil",
  "93X": "Mitsubishi Motors Brazil",
  "93Y": "Renault",
  "94D": "Nissan Brazil",
  "9BD": "Fiat",
  "9BF": "Ford",
  "9BG": "Chevrolet",
  "9BM": "Mercedes-Benz",
  "9BR": "Toyota Brazil",
  "9BS": "Scania",
  "9BW": "Volkswagen",
  "9C2": "Honda",
  "9DB": "Mercedes-Benz",
  "9DW": "Volkswagen",
  "9FB": "Renault",
  "AAV": "Volkswagen",
  "AC5": "Hyundai",
  "ADD": "Hyundai",
  "ADM": "General Motors",
  "AFA": "Ford",
  "AHT": "Toyota",
  "CL9": "Wallyscar",
  "J81": "Chevrolet",
  "J87": "Isuzu",
  "J8B": "Chevrolet",
  "J8C": "Chevrolet",
  "J8D": "GMC",
  "J8Y": "Chevrolet",
  "J8Z": "Chevrolet",
  "JA": "Isuzu",
  "JA3": "Mitsubishi",
  "JA4": "Mitsubishi",
  "JA7": "Mitsubishi",
  "JAA": "Isuzu",
  "JAB": "Isuzu",
  "JAC": "Isuzu",
  "JAE": "Acura",
  "JAL": "Isuzu",
  "JB3": "Dodge",
  "JB4": "Dodge",
  "JB7": "Dodge",
  "JC2": "Ford",
  "JD": "Daihatsu",
  "JD1": "Daihatsu",
  "JD2": "Daihatsu",
  "JE3": "Eagle",
  "JF": "Fuji Heavy Industries (Subaru)",
  "JF1": "Subaru",
  "JF2": "Subaru",
  "JF3": "Subaru",
  "JF4": "Saab",
  "JG1": "Chevrolet",
  "JG7": "Pontiac",
  "JGC": "Chevrolet",
  "JH": "Honda",
  "JH2": "Honda",
  "JH3": "Honda",
  "JH4": "Acura",
  "JHB": "Hino",
  "JHK": "Honda",
  "JHL": "Honda",
  "JHM": "Honda",
  "JJ3": "Chrysler",
  "JK": "Kawasaki (motorcycles)",
  "JK8": "Suzuki",
  "JKS": "Suzuki",
  "JL5": "Mitsubishi",
  "JL6": "Mitsubishi",
  "JLS": "Sterling",
  "JM1": "Mazda",
  "JM2": "Mazda",
  "JM3": "Mazda",
  "JMB": "Mitsubishi",
  "JMY": "Mitsubishi Motors",
  "JMZ": "Mazda",
  "JN": "Nissan",
  "JDA": "Daihatsu",
  "JMF": "Mitsubishi",
  "JMP": "Mitsubishi",
  "JN1": "Nissan",
  "JN3": "Nissan",
  "JN4": "Nissan",
  "JN6": "Datsun",
  "JN8": "Nissan",
  "JNA": "Nissan",
  "JNK": "Infiniti",
  "JNR": "Infiniti",
  "JNX": "Infiniti",
  "JP3": "Plymouth",
  "JP4": "Plymouth",
  "JP7": "Plymouth",
  "JS": "Suzuki",
  "JS1": "Suzuki",
  "JS2": "Suzuki",
  "JS3": "Suzuki",
  "JS4": "Suzuki",
  "JSA": "Suzuki",
  "JSL": "Suzuki",
  "JT": "Toyota",
  "JT2": "Toyota",
  "JT3": "Toyota",
  "JT4": "Toyota",
  "JT5": "Toyota",
  "JT6": "Lexus",
  "JT8": "Lexus",
  "JT1": "Toyota",
  "JTD": "Toyota",
  "JTE": "Toyota",
  "JTH": "Lexus",
  "JTJ": "Lexus",
  "JTK": "Toyota",
  "JTL": "Scion",
  "JTM": "Toyota",
  "JTN": "Toyota",
  "JW6": "Mitsubishi",
  "JW7": "Mitsubishi",
  "JY": "Yamaha (motorcycles)",
  "KL": "Daewoo General Motors South Korea",
  "KL1": "Chevrolet",
  "KL2": "Pontiac",
  "KL5": "Suzuki",
  "KL7": "Asuna",
  "KLA": "Daewoo",
  "KM": "Hyundai",
  "KM1": "Suzuki",
  "KM4": "Suzuki",
  "KM8": "Hyundai",
  "KMF": "Hyundai",
  "KMH": "Hyundai",
  "KMJ": "Hyundai",
  "KNE": "Kia",
  "KMY": "Daelim (motorcycles)",
  "KN": "Kia",
  "KNA": "Kia",
  "KNB": "Kia",
  "KNC": "Kia",
  "KND": "Hyundai",
  "KNJ": "Ford",
  "KNM": "Renault Samsung",
  "KPA": "Ssangyong",
  "KPH": "Mitsubishi",
  "KPT": "SsangYong",
  "L4B": "Xingyue Group (motorcycles)",
  "L56": "Renault Samsung",
  "L5C": "KangDi (ATV)",
  "L5K": "Zhejiang Yongkang Easy Vehicle",
  "L5N": "Zhejiang Taotao",
  "L5Y": "Merato Motorcycle Taizhou Zhongneng",
  "L85": "Zhejiang Yongkang Huabao Electric Appliance",
  "L8X": "Zhejiang Summit Huawin Motorcycle",
  "LAN": "Changzhou Yamasaki Motorcycle",
  "LB2": "Geely Motorcycles",
  "LBB": "Zhejiang Qianjiang Motorcycle (Keeway/Generic)",
  "LBE": "Beijing Hyundai",
  "LBM": "Zongshen Piaggio",
  "LBP": "Chongqing Jainshe Yamaha (motorcycles)",
  "LCE": "Hangzhou Chunfeng Motorcycles (CFMOTO)",
  "LDC": "Dong Feng Peugeot Citroen (DPCA)",
  "LDD": "Dandong Huanghai Automobile",
  "LDN": "SouEast Motor",
  "LDY": "Zhongtong Coach",
  "LE4": "Beijing Benz",
  "LES": "Isuzu",
  "LET": "Jiangling-Isuzu Motors",
  "LFB": "FAW",
  "LFG": "Taizhou Chuanl Motorcycle Manufacturing",
  "LFP": "FAW",
  "LFT": "FAW",
  "LFV": "FAW-Volkswagen",
  "LFW": "FAW JieFang",
  "LFY": "Changshu Light Motorcycle Factory",
  "LGB": "Dong Feng (DFM)",
  "LGH": "Dong Feng (DFM)",
  "LGX": "BYD Auto",
  "LH1": "FAW-Haima",
  "LHB": "Beijing Automotive Industry Holding",
  "LJ1": "JAC",
  "LJC": "JAC",
  "LKL": "Suzhou King Long",
  "LL6": "Hunan Changfeng Manufacture Joint-Stock",
  "LL8": "Linhai (ATV)",
  "LM1": "Suzuki",
  "LM4": "Suzuki",
  "LM5": "Isuzu",
  "LMC": "Suzuki Hong Kong (motorcycles)",
  "LN1": "Suzuki",
  "LPR": "Yamaha Hong Kong (motorcycles)",
  "LSG": "Shanghai General Motors",
  "LSJ": "MG Motor UK Limited - SAIC Motor",
  "LSV": "Shanghai Volkswagen",
  "LSY": "Brilliance Zhonghua",
  "LTV": "Toyota Tian Jin",
  "L6T": "Lynk & Co",
  "LUC": "Honda",
  "LVS": "Ford Chang An",
  "LVV": "Chery",
  "LVY": "Volvo",
  "LVZ": "DFSK",
  "LWV": "JEEP",
  "LZE": "Isuzu Guangzhou",
  "LZG": "Shaanxi Automobile Group",
  "LZM": "MAN China",
  "LZP": "Zhongshan Guochi Motorcycle (Baotian)",
  "LZY": "Yutong Zhengzhou",
  "LZZ": "Chongqing Shuangzing Mech & Elec (Howo)",
  "MA1": "Mahindra",
  "MA3": "Suzuki",
  "MA6": "GM India",
  "MA7": "Honda",
  "MAB": "Mahindra & Mahindra",
  "MAC": "Mahindra & Mahindra",
  "MAJ": "Ford India",
  "MAK": "Honda Siel Cars India",
  "MAL": "Hyundai",
  "MAT": "Tata Motors",
  "MB1": "Ashok Leyland",
  "MBH": "Nissan",
  "MMS": "Suzuki",
  "MBJ": "Toyota India",
  "MBR": "Mercedes-Benz India",
  "MC2": "Volvo Eicher commercial vehicles limited.",
  "MCA": "Fiat India",
  "MCB": "GM India",
  "MD2": "Bajaj Auto",
  "MDH": "Nissan",
  "MEE": "Renault",
  "MEX": "Volkswagen",
  "MHF": "Toyota Indonesia",
  "MHR": "Honda",
  "ML3": "Dodge",
  "MLC": "Suzuki",
  "MLH": "Honda",
  "MM8": "Mazda",
  "MMB": "Mitsubishi",
  "MMC": "Mitsubishi",
  "MMM": "Chevrolet",
  "MMT": "Mitsubishi",
  "MNB": "Ford",
  "MNT": "Nissan",
  "MP1": "Isuzu",
  "MPA": "Isuzu",
  "MR0": "Toyota",
  "MRH": "Honda",
  "NLA": "Honda",
  "NLE": "Mercedes-Benz",
  "NLH": "Hyundai",
  "NM0": "Ford",
  "NM4": "Tofas",
  "NMT": "Toyota",
  "PE1": "Ford",
  "PE3": "Mazda",
  "PL1": "Proton",
  "PNA": "NAZA",
  "RF3": "Aeon Motor",
  "RFB": "Kymco",
  "RFG": "Sanyang SYM",
  "RFL": "Adly",
  "RFT": "CPI",
  "SA9": "Morgan",
  "SAJ": "Jaguar",
  "SAL": "Land Rover",
  "SAR": "Rover",
  "SAT": "Triumph",
  "SAX": "Sterling",
  "SB1": "Toyota",
  "SBM": "McLaren",
  "SCA": "Rolls-Royce",
  "SCB": "Bentley",
  "SCC": "Lotus",
  "SCE": "DeLorean",
  "SCF": "Aston Martin",
  "SDB": "Peugeot",
  "SED": "General Motors Luton Plant",
  "SEY": "LDV",
  "SFA": "Ford UK",
  "SFD": "Alexander Dennis",
  "SHH": "Honda",
  "SHS": "Honda",
  "SJN": "Nissan",
  "SKF": "Vauxhall",
  "SLP": "JCB Research UK",
  "SMT": "Triumph Motorcycles",
  "SU9": "Solaris",
  "SUF": "Fiat Auto Poland",
  "SUL": "FSC (Poland)",
  "SUP": "FSO-Daewoo (Poland)",
  "SUU": "Solaris Bus & Coach (Poland)",
  "TCC": "SMART",
  "TDM": "QUANTYA",
  "TK9": "SOR",
  "TM9": "Skoda",
  "TMA": "Hyundai",
  "TMB": "Skoda",
  "TMK": "Karosa",
  "TMP": "Skoda",
  "TMT": "Tatra",
  "TN9": "Karosa",
  "TNE": "TAZ",
  "TRA": "Ikarus",
  "TRU": "Audi",
  "TSE": "Ikarus",
  "TSM": "Suzuki",
  "TW1": "Toyota",
  "TYA": "Mitsubishi",
  "TYB": "Mitsubishi",
  "U5Y": "Kia",
  "U6Y": "Kia",
  "UU1": "Renault Dacia",
  "UU3": "ARO",
  "UU6": "Daewoo",
  "VAG": "Magna Steyr Puch",
  "VAN": "MAN Austria",
  "VBK": "KTM",
  "VF1": "Renault",
  "VF2": "Renault",
  "VF3": "Peugeot",
  "VF4": "Talbot",
  "VF6": "Renault",
  "VF7": "Citroën",
  "VF8": "Matra",
  "VFE": "IvecoBus",
  "VG5": "MBK (motorcycles)",
  "VG6": "Mack",
  "VLU": "Scania",
  "VN1": "SOVAB",
  "VNE": "Irisbus",
  "VNK": "Toyota",
  "VNV": "Nissan",
  "VS6": "Ford",
  "VS9": "Carrocerias Ayats",
  "VSA": "Mercedes-Benz",
  "VSE": "Suzuki",
  "VSK": "Nissan",
  "VSS": "SEAT",
  "VSX": "Opel",
  "VTH": "Derbi (motorcycles)",
  "VTM": "Honda",
  "VTT": "Suzuki",
  "VV9": "Tauro Sport Auto",
  "VWA": "Nissan",
  "VWV": "Volkswagen",
  "VX1": "Zastava",
  "W06": "Cadillac",
  "W0L": "Opel",
  "WA1": "Audi",
  "WAG": "Neoplan",
  "WAP": "Alpina",
  "WAU": "Audi",
  "WB1": "BMW",
  "WBA": "BMW",
  "WBS": "BMW",
  "WBX": "BMW",
  "WBY": "BMW",
  "WD0": "Dodge",
  "WD1": "Dodge",
  "WD2": "Dodge",
  "WD3": "Mercedes-Benz",
  "WD4": "Mercedes-Benz",
  "WD5": "Dodge",
  "WD8": "Dodge",
  "WDA": "Mercedes-Benz",
  "WDB": "Mercedes-Benz",
  "W1K": "Mercedes-Benz",
  "WDC": "Mercedes-Benz",
  "WDD": "Mercedes-Benz",
  "WDF": "Mercedes-Benz",
  "WDP": "Dodge",
  "WDX": "Dodge",
  "WDY": "Dodge",
  "WDZ": "Mercedes-Benz",
  "WEB": "EvoBus",
  "WF0": "Ford",
  "WF1": "Merkur",
  "WJM": "Iveco",
  "WJR": "Irmscher",
  "WKK": "Fahrzeugwerke",
  "WMA": "MAN",
  "WME": "Mercedes-Benz",
  "WMW": "Mini",
  "WMX": "Mercedes-Benz",
  "WP0": "Porsche",
  "WP1": "Porsche",
  "WUA": "Audi",
  "WV1": "Volkswagen",
  "WV2": "Volkswagen",
  "WV3": "Volkswagen",
  "WVG": "Volkswagen",
  "WVW": "Volkswagen",
  "X4X": "AvtoTor",
  "X7L": "Renault",
  "X7M": "Hyundai",
  "XL9": "Spyker",
  "XLB": "Volvo",
  "XLE": "Scania",
  "XLR": "DAF",
  "XMC": "Mitsubishi",
  "XNC": "Mitsubishi",
  "XTA": "Lada",
  "XTT": "UAZ/Sollers",
  "XUF": "General Motors",
  "XUU": "AvtoTor",
  "XW8": "Volkswagen",
  "XWB": "UZ-Daewoo",
  "XWE": "AvtoTor",
  "Y6D": "Zaporozhets",
  "YB3": "Volvo",
  "YBW": "Volkswagen",
  "YC1": "Honda",
  "YCM": "Mazda",
  "YE2": "Van Hool",
  "YK1": "Saab",
  "YS2": "Scania",
  "YS3": "Saab",
  "YS4": "Scania",
  "YTN": "Saab",
  "YU7": "Husaberg (motorcycles)",
  "YV1": "Volvo",
  "YV2": "Volvo",
  "YV3": "Volvo",
  "YV4": "Volvo",
  "YV5": "Volvo",
  "Z8M": "Marussia",
  "ZA9": "Lamborghini",
  "ZAA": "Autobianchi",
  "ZAM": "Maserati",
  "ZAP": "Piaggio/Vespa/Gilera",
  "ZAR": "Alfa Romeo",
  "ZBN": "Benelli",
  "ZC2": "Chrysler",
  "ZCF": "Iveco",
  "ZCG": "Cagiva",
  "ZD0": "Yamaha",
  "ZD3": "Beta Motor",
  "ZD4": "Aprilia",
  "ZDC": "Honda",
  "ZDF": "Ferrari",
  "ZDM": "Ducati",
  "ZAC": "Jeep",
  "ZFA": "Fiat",
  "ZFB": "Fiat",
  "ZFC": "Fiat",
  "ZFF": "Ferrari",
  "ZGA": "Iveco",
  "ZGU": "Moto Guzzi",
  "ZHW": "Lamborghini",
  "ZJM": "Malaguti",
  "ZJN": "Innocenti",
  "ZKH": "Husqvarna",
  "ZLA": "Lancia",
  "ZOM": "OM",
  // ===== Bulk import from Wikibooks WMI table 2026-04-26 =====
  // Source: en.wikibooks.org/wiki/Vehicle_Identification_Numbers_(VIN_codes)/
  //         World_Manufacturer_Identifier_(WMI)
  // 1373 entries not previously in our universal map. Mostly niche
  // OEMs, regional sub-brands, and commercial-vehicle / trailer
  // manufacturers. Make labels lightly cleaned (legal forms stripped).
  "10B": "Brenner Tank (truck trailer)",
  "10R": "E-Z-GO",
  "11H": "Hendrickson Mobile Equipment, Inc. (fire engines - incomplete vehicle)",
  "12A": "Avanti",
  "13N": "Fontaine (truck trailer)",
  "16C": "Clenet Coachworks",
  "16W": "Certified Stainless Services Inc. DBA West-Mark (truck trailer) (prior to 2010)",
  "16X": "Vixen 21 motorhome",
  "19V": "Acura car made by Honda Manufacturing of Indiana",
  "19X": "Honda car made by Honda Manufacturing of Indiana",
  "1AF": "American LaFrance truck",
  "1AJ": "Ajax Manufacturing (truck trailer)",
  "1BL": "Balko",
  "1BN": "Beall Trailers (truck trailer)",
  "1CM": "Checker Motors Corporation",
  "1CU": "Cushman Haulster (Cushman division of Outboard Marine Corporation)",
  "1DW": "Stoughton Trailers (truck trailer)",
  "1EU": "Eagle Coach Corporation (bus)",
  "1G0": "Opel/Vauxhall car 2007–2017",
  "1G7": "Pontiac car only sold by GM Canada",
  "1GR": "Great Dane Trailers (truck trailer)",
  "1HA": "Chevrolet incomplete vehicles made by Navistar International",
  "1JJ": "Wabash (truck trailer)",
  "1JU": "Marmon Motor Company",
  "1L0": "Lufkin Trailers",
  "1LH": "Landoll (truck trailer)",
  "1LJ": "Lincoln incomplete vehicle",
  "1LV": "Lectra Motors",
  "1M0": "John Deere Gator",
  "1NL": "Gulf Stream Coach (recreational vehicles)",
  "1NN": "Monon made by Evans Products Co. (truck trailer)",
  "1PM": "Polar Tank Trailer (truck trailer)",
  "1PT": "Trailmobile Trailer Corporation (truck trailer)",
  "1PY": "John Deere USA",
  "1RN": "Reitnouer (truck trailer)",
  "1S1": "Strick Trailers (truck trailer)",
  "1ST": "Airstream (recreational vehicles)",
  "1T7": "Thomas Built Buses",
  "1TC": "Coachmen Recreational Vehicle Co",
  "1TD": "Transcraft Corporation (truck trailer)",
  "1TK": "Trail King (truck trailer)",
  "1UJ": "Jayco",
  "1UT": "AM General military trucks, Jeep DJ made by AM General",
  "1UY": "Utility Trailer (truck trailer)",
  "1V2": "Volkswagen SUV",
  "1VH": "Orion Bus Industries",
  "1W1": "Wilson Trailer Co. (truck trailer)",
  "1W8": "Witzco (truck trailer)",
  "1WT": "Winnebago Industries",
  "1XA": "Excalibur Automobile Corporation",
  "1YJ": "Rokon International",
  "2BP": "Ski-Doo",
  "2BV": "Can-Am & Bombardier ATV",
  "2BW": "Can-Am Commander E LSV",
  "2BX": "Can-Am Spyder",
  "2BZ": "Can-Am Freedom Trailer for Can-Am Spyder",
  "2CG": "Asüna/Pontiac SUV made by CAMI Automotive only sold by GM Canada",
  "2CT": "GMC Terrain SUV made by CAMI Automotive 2010–2011 only",
  "2DG": "Ontario Drive & Gear",
  "2DM": "Di-Mond Trailers (truck trailer)",
  "2DN": "Dynasty Electric Car Corporation",
  "2E4": "2011 Lancia MPV (Voyager)",
  "2EZ": "Electra Meccanica Vehicles Corp. (Solo)",
  "2FH": "Zenn Motor Co., Ltd. (low-speed vehicle)",
  "2FY": "New Flyer",
  "2G6": "Cadillac car",
  "2GE": "Cadillac incomplete vehicle",
  "2GH": "GMC GM New Look bus & GM Classic series bus",
  "2L1": "Lincoln incomplete vehicle – limo",
  "2LD": "Triple E Canada Ltd",
  "2LJ": "Lincoln incomplete vehicle – hearse",
  "2LN": "Lincoln car",
  "2M1": "Mack Trucks",
  "2MG": "Motor Coach Industries (Produced from Sept. 1, 2008 on)",
  "2TU": "Tri-Star Industries Limited",
  "3AK": "Freightliner Trucks",
  "3AW": "Fruehauf de Mexico (truck trailer)",
  "3AX": "Scania Mexico",
  "3BE": "Scania Mexico (buses)",
  "3BJ": "Western Star 3700 truck made by DINA S.A",
  "3BM": "Motor Coach Industries bus made by DINA S.A",
  "3C6": "Chrysler Group (all brands) truck 2012–",
  "3C7": "Chrysler Group (all brands) incomplete vehicle 2012–",
  "3CG": "KTMMEX S.A. de C.V",
  "3D2": "Dodge incomplete vehicle 2007–2009",
  "3D4": "Dodge SUV 2009–2011",
  "3E4": "2011 Fiat SUV (Freemont)",
  "3EL": "ATRO (truck trailer)",
  "3F6": "Sterling Bullet",
  "3FM": "Ford MPV/SUV",
  "3FN": "Ford F-650/F-750 made by Blue Diamond Truck Co. (truck)",
  "3G0": "Holden Equinox 2018–2020",
  "3GP": "Honda Prologue EV made by GM",
  "3GS": "Saturn SUV",
  "3H3": "Hyundai de Mexico, S.A. de C.V. for Hyundai Translead (truck trailers)",
  "3HC": "International Trucks truck",
  "3HD": "Acura SUV made by Honda de Mexico",
  "3HV": "International incomplete bus",
  "3KM": "Kia/Hyundai MPV/SUV made by KMMX",
  "3KP": "Kia/Hyundai car made by KMMX",
  "3MF": "BMW M car",
  "3MG": "Isuzu Motors de Mexico",
  "3MJ": "Mazda CX-3 (Mazda de Mexico)",
  "3MW": "BMW car",
  "3MY": "Toyota car made by Mazda de Mexico Vehicle Operation",
  "3NE": "Polaris Industries UTV",
  "3NS": "Polaris Industries ATV",
  "3PC": "Infiniti SUV made by COMPAS",
  "3TY": "Toyota truck made by TMMGT",
  "3VV": "Volkswagen Mexico SUV",
  "3WP": "Peterbilt truck",
  "43C": "Consulier",
  "44K": "HME Inc. (fire engines - incomplete vehicle) (HME=Hendrickson Mobile Equipment)",
  "46J": "Federal Motors",
  "480": "Sterling Trucks (truck)",
  "4C6": "Reinke Manufacturing Company (truck trailer)",
  "4EN": "E-ONE, Inc. (fire engines - truck)",
  "4G3": "Toyota Cavalier made by GM",
  "4G5": "General Motors EV1",
  "4GL": "Buick incomplete vehicle",
  "4J8": "LBT, Inc. (truck trailer)",
  "4KE": "U.S. Electricar Consulier",
  "4LM": "Capacity of Texas (truck)",
  "4ML": "Oshkosh Trailer Division",
  "4MZ": "Buell Motorcycle Company",
  "4P1": "Pierce Manufacturing Inc. USA",
  "4T4": "Toyota car made by Subaru of Indiana Automotive",
  "4V0": "Crossroads RV (recreational vehicles)",
  "4VE": "Volvo Trucks North America (incomplete vehicle)",
  "4W1": "'24+ Chevrolet Suburban HD made by GM Defense for US govt. in Concord, NC",
  "4W5": "Acura ZDX EV made by GM",
  "4WW": "Wilson Trailer Sales",
  "4X4": "Forest River",
  "4XA": "Polaris",
  "4YD": "KeyStone RV Company (recreational vehicle)",
  "4YM": "Anderson Manufacturing (trailer)",
  "4Z3": "American LaFrance truck",
  "50E": "Lucid Motors passenger car",
  "50G": "Karma Automotive",
  "516": "Autocar truck",
  "51R": "Brammo Motorcycles",
  "522": "GreenGo Tek (low-speed vehicle)",
  "523": "VPG (The Vehicle Production Group)",
  "52C": "GEM subsidiary of Polaris",
  "537": "Azure Dynamics Transit Connect Electric",
  "53G": "Coda Automotive",
  "53T": "Think North America in Elkhart, IN",
  "546": "EBR",
  "54C": "Winnebago Industries travel trailer",
  "54D": "Isuzu & Chevrolet commercial trucks built by Spartan Motors/The Shyft Group",
  "54F": "Rosenbauer",
  "55S": "Mercedes-Benz car",
  "56K": "Indian Motorcycle International, (Polaris subsidiary)",
  "573": "Grand Design RV (truck trailer)",
  "57C": "Maurer Manufacturing (truck trailer)",
  "57R": "Oreion Motors",
  "57S": "Lightning Motors Corp. (electric motorcycles)",
  "57W": "Mobility Ventures",
  "57X": "Polaris Slingshot",
  "58A": "Lexus car made by TMMK (Lexus ES)",
  "5A4": "Load Rite Trailers",
  "5AX": "Armor Chassis (truck trailer)",
  "5BP": "Solectria",
  "5BZ": "Nissan bus (van with more than 3 rows of seats)",
  "5CD": "Indian Motorcycle Company of America (Gilroy, CA)",
  "5CX": "Shelby Series 1",
  "5DF": "Thomas Dennis Company",
  "5DG": "Terex Advance Mixer",
  "5EH": "Excelsior-Henderson Motorcycle",
  "5EO": "Cottrell (truck trailer)",
  "5FC": "Columbia Vehicle Group (Columbia, Tomberlin) (low-speed vehicles)",
  "5FR": "Acura SUV made by Honda Manufacturing of Alabama",
  "5FT": "Feeling Trailers",
  "5G8": "Holden Volt",
  "5GD": "Daewoo G2X",
  "5GN": "Hummer H3T",
  "5HD": "Harley-Davidson for export markets",
  "5HT": "Heil Trailer (truck trailer)",
  "5J5": "Club Car",
  "5KM": "Vento Motorcycles",
  "5KT": "Karavan Trailers",
  "5L1": "Lincoln SUV - Limousine (2004–2009)",
  "5L5": "American IronHorse Motorcycle",
  "5LD": "Ford & Lincoln incomplete vehicle – limousine (2010–2014)",
  "5MZ": "Buell Motorcycle Company for export markets",
  "5NH": "Forest River",
  "5NT": "Hyundai truck made by HMMA",
  "5RJ": "Android Industries",
  "5RX": "Heartland Recreational Vehicles",
  "5TU": "Construction Trailer Specialist (truck trailer)",
  "5V8": "Vanguard National (truck trailer)",
  "5VC": "Autocar incomplete vehicle",
  "5VF": "American Electric Vehicle Company (low-speed vehicle)",
  "5VP": "Victory Motorcycles",
  "5WE": "IC Bus incomplete vehicle",
  "5XX": "Kia car made by KMMG",
  "5Y4": "Yamaha Motor Motor Mfg. Corp. of America (ATV, UTV)",
  "5YA": "Indian Motorcycle Company (Kings Mountain, NC)",
  "5YF": "Toyota car made by TMMMS",
  "5YN": "Cruise Car",
  "5ZT": "Forest River (recreational vehicles)",
  "5ZU": "Greenkraft (truck)",
  "6AM": "Jayco Corp. (RVs)",
  "6F1": "Ford",
  "6F2": "Iveco Trucks Australia Ltd",
  "6FM": "Mack Trucks Australia",
  "6G3": "General Motors Chevrolet Caprice PPV & SS performance sedan 2014-2017",
  "6KT": "BCI Bus",
  "6T9": "Privately Imported car (VIN issued by Victoria) or Trailer in Australia",
  "6ZZ": "Privately Imported car in Australia",
  "722": "Isuzu North America Corp. (incomplete vehicle - medium duty)",
  "7A1": "Mitsubishi New Zealand",
  "7A3": "Honda New Zealand",
  "7A4": "Toyota New Zealand",
  "7A5": "Ford New Zealand",
  "7A7": "Nissan New Zealand",
  "7A8": "VIN assigned by the New Zealand Transport Authority Waka Kotahi before 29 November 2009",
  "7AB": "MAN New Zealand",
  "7AT": "VIN assigned by the New Zealand Transport Authority Waka Kotahi from 29 November 2009",
  "7B2": "Nissan Diesel bus New Zealand",
  "7F7": "Arcimoto",
  "7FA": "Honda SUV made by Honda Manufacturing of Indiana",
  "7FC": "Rivian truck",
  "7G0": "Faraday Future",
  "7G2": "Tesla, Inc. truck (used for Nevada-built Semi Trucks & Texas-built Cybertruck)",
  "7GZ": "GMC incomplete vehicles made by Navistar International",
  "7H4": "Hino truck",
  "7H8": "Cenntro Electric Group Limited low-speed vehicle",
  "7JD": "Volvo Cars SUV",
  "7JR": "Volvo Cars passenger car",
  "7JZ": "Proterra From mid-2019 on",
  "7KG": "Vanderhall Motor Works",
  "7KY": "Dorsey (truck trailer)",
  "7MM": "Mazda SUV made by MTMUS (Mazda-Toyota Joint Venture)",
  "7MU": "Toyota SUV made by MTMUS (Mazda-Toyota Joint Venture)",
  "7MW": "Cenntro Electric Group Limited truck",
  "7MZ": "HDK electric vehicles",
  "7NA": "Navistar Defense",
  "7NY": "Lordstown Motors",
  "7PD": "Rivian SUV",
  "7RZ": "Electric Last Mile Solutions",
  "7SA": "Tesla, Inc. (US-built MPVs (e.g. Model X, Model Y))",
  "7SU": "Blue Arc electric trucks made by The Shyft Group",
  "7SV": "Toyota SUV made by TMMTX",
  "7SX": "Global Electric Motorcars (WAEV) 2022-",
  "7SY": "Polestar SUV",
  "7TN": "Canoo",
  "7UU": "Lucid Motors MPV/SUV",
  "7UZ": "Kaufman Trailers (trailer)",
  "7VV": "Ree Automotive",
  "7WE": "Bollinger Motors incomplete vehicle",
  "7YA": "Hyundai MPV/SUV made by HMGMA",
  "7Z0": "Zoox",
  "829": "Industrias Quantum Motors S.A. (Bolivia)",
  "8A3": "Scania Argentina",
  "8AB": "Mercedes Benz truck & bus (Argentina)",
  "8AC": "Mercedes Benz vans (for South America)",
  "8AE": "Peugeot van",
  "8AN": "Nissan Argentina",
  "8AT": "Iveco Argentina",
  "8BB": "Agrale Argentina S.A",
  "8BC": "Citroën Argentina",
  "8BN": "Mercedes-Benz incomplete vehicle (North America)",
  "8BR": "Mercedes-Benz bus (van with more than 3 rows of seats) (North America)",
  "8BT": "Mercedes-Benz MPV (van with 2 or 3 rows of seats) (North America)",
  "8BU": "Mercedes-Benz truck (cargo van with 1 row of seats) (North America)",
  "8C3": "Honda car/SUV",
  "8CH": "Honda motorcycle",
  "8G1": "Automotores Franco Chilena S.A. Renault",
  "8L4": "Great Wall Motors made by Ciudad del Auto (Ciauto)",
  "8LD": "General Motors OBB - Chevrolet Ecuador",
  "8LF": "Maresa (Mazda)",
  "8LG": "Aymesa (Hyundai Motor & Kia)",
  "8XD": "Ford Motor Venezuela",
  "8XJ": "Mack de Venezuela C.A",
  "8XV": "Iveco Venezuela C.A",
  "8Z1": "General Motors Venezolana C.A",
  "92H": "Origem Brazil",
  "932": "Harley-Davidson Brazil",
  "937": "Dodge Dakota",
  "93C": "Chevrolet SUV [Tracker] or pickup [Tornado, Montana, S10] (sold in Mexico, made in Brazil)",
  "93K": "Volvo Trucks",
  "93P": "Volare",
  "93S": "Navistar International",
  "93W": "Fiat Ducato made by Iveco 2000–2016",
  "93Z": "Iveco",
  "94N": "RWM Brazil",
  "94T": "Troller Veículos Especiais",
  "953": "VW Truck & Bus / MAN Truck & Bus",
  "95P": "CAOA Hyundai & CAOA Chery",
  "95V": "BMW motorcycles assembled by Dafra Motos 2009–2016",
  "95Z": "Buell Motorcycle Company assembled by Harley-Davidson Brazil",
  "96P": "Kawasaki",
  "97N": "Triumph Motorcycles Ltd",
  "988": "Jeep, Ram [Rampage], and Fiat [Toro] (made at the Goiana plant)",
  "98M": "BMW car/SUV",
  "98P": "DAF Trucks",
  "98R": "Chery",
  "99A": "Audi 2016-",
  "99H": "Shineray",
  "99J": "Jaguar Land Rover",
  "99K": "Haojue & Kymco assembled by JTZ Indústria e Comércio de Motos",
  "99L": "BYD",
  "99Z": "BMW Motorrad (Motorcycle assembled by BMW 2017-)",
  "9BH": "Hyundai Motor Brasil",
  "9BN": "Mafersa",
  "9BV": "Volvo Trucks",
  "9BY": "Agrale S.A",
  "9C6": "Yamaha Motor Da Amazonia Ltda",
  "9CD": "Suzuki (motorcycles) assembled by J. Toledo Motos do Brasil",
  "9DF": "Puma",
  "9EZ": "homemade or handbuilt vehicles",
  "9FC": "Compañía Colombiana Automotriz S.A. (Mazda)",
  "9GA": "Chevrolet Colombia (GM Colmotores S.A.)",
  "9UJ": "Chery assembled by Chery Socma S.A. (Uruguay)",
  "9UK": "Lifan (Uruguay)",
  "9UT": "Dongfeng trucks made by Nordex S.A",
  "9UW": "Kia made by Nordex S.A",
  "9V7": "Citroen made by Nordex S.A. (Jumpy)",
  "9V8": "Peugeot made by Nordex S.A. (Expert)",
  "9VC": "Fiat made by Nordex S.A. (Scudo, 2025 Titano)",
  "AAA": "Audi South Africa made by Volkswagen of South Africa",
  "AAK": "FAW Vehicle Manufacturers SA (PTY) Ltd",
  "AAM": "MAN Automotive (South Africa) (Pty) Ltd. (includes VW Truck & Bus)",
  "AAP": "VIN restamped by South African Police Service (so-called SAPVIN or AAPV number)",
  "AAW": "Challenger Trailer (South Africa)",
  "ABJ": "Mitsubishi Fuso made by Daimler Trucks & Buses Southern Africa",
  "ABM": "BMW Southern Africa",
  "ACV": "Isuzu Motors South Africa 2018-",
  "ADB": "Mercedes-Benz South Africa car",
  "ADN": "Nissan South Africa (Pty) Ltd",
  "ADR": "Renault Sandero made by Nissan South Africa (Pty) Ltd",
  "ADX": "Tata Automobile Corporation (SA) Ltd",
  "AFB": "Mazda BT-50 made by Ford Motor Company of Southern Africa",
  "AFD": "BAIC Automotive South Africa",
  "AFZ": "Fiat Auto South Africa",
  "AHH": "Hino South Africa",
  "AHM": "Honda Ballade made by Mercedes-Benz South Africa 1982–2000",
  "BR1": "Mercedes-Benz Algeria (SAFAV MB)",
  "BRY": "FIAT Algeria",
  "BUK": "Kiira Motors Corporation, Uganda",
  "CA3": "MCV bus (Egypt)",
  "DDY": "Geyushi Motors (bus) (Egypt)",
  "EAA": "Aurus Motors (Russia)",
  "EAN": "Evolute (Russia)",
  "EAU": "Elektromobili Manufacturing Rus - EVM (Russia)",
  "EBE": "Sollers-Auto (Russia)",
  "EBZ": "Nizhekotrans bus (Russia)",
  "ECE": "XCITE (Russia)",
  "ECW": "Trans-Alfa bus (Russia)",
  "H0D": "Taizhou Qianxin Vehicle Co., Ltd. (motorcycle)",
  "H0G": "Wisdom (Fujian) Motor Co., Ltd. (bus)",
  "HA0": "Wuxi Sundiro Electric Vehicle Co., Ltd. (Palla, Parray)",
  "HA6": "Niu Technologies",
  "HA7": "Jinan Qingqi KR Motors",
  "HES": "smart Automobile Co., Ltd. (Mercedes-Geely joint venture)",
  "HGL": "Farizon Auto van (Geely)",
  "HGX": "Wuling Motors commercial vehicle (Geely)",
  "HHZ": "Huazi Automobile",
  "HJ4": "BAW car",
  "HJN": "Nio, Firefly",
  "HJR": "Chery Commercial Vehicle (Anhui) Co., Ltd. Jetour made by Chery Commercial Vehicle",
  "HJZ": "Juzhen Chengshi van",
  "HL4": "Zhejiang Morini Vehicle Co., Ltd. (Moto Morini subsidiary of Taizhou Zhongneng Motorcycle ",
  "HLX": "Li Auto",
  "HRV": "Beijing Henrey Automobile Technology",
  "HVW": "Volkswagen Anhui",
  "HWM": "WM Motor Technology Co., Ltd. (Weltmeister)",
  "HXM": "Xiaomi",
  "HZ2": "Taizhou Zhilong Technology Co., Ltd (motorcycle)",
  "J8T": "GMC commercial trucks made by Isuzu (truck)",
  "JAM": "Isuzu commercial trucks (Incomplete Vehicle - light duty)",
  "JC0": "Ford brand cars made by Mazda",
  "JC1": "Fiat 124 Spider made by Mazda",
  "JD4": "Daihatsu truck",
  "JE4": "Mitsubishi Motors",
  "JG2": "Pontiac car made by Suzuki",
  "JGT": "GMC SUV made by Suzuki for GM Canada (classified as a truck)",
  "JH1": "Honda truck",
  "JH6": "Hino incomplete vehicle",
  "JHA": "Hino truck",
  "JHD": "Hino",
  "JHF": "Hino",
  "JHH": "Hino incomplete vehicle",
  "JKA": "Kawasaki (motorcycles)",
  "JKB": "Kawasaki (motorcycles)",
  "JKM": "Mitsuoka",
  "JL7": "Mitsubishi Fuso Truck & Bus Corp",
  "JLB": "Mitsubishi Fuso Truck & Bus Corp",
  "JLF": "Mitsubishi Fuso Truck & Bus Corp",
  "JM0": "Mazda for Oceania export",
  "JM4": "Mazda",
  "JM6": "Mazda",
  "JM7": "Mazda",
  "JMA": "Mitsubishi Motors (right-hand drive) for Europe",
  "JMR": "Mitsubishi Motors (right-hand drive)",
  "JNC": "Nissan Diesel/UD Trucks",
  "JNE": "Nissan Diesel/UD Trucks truck",
  "JPC": "Nissan Diesel/UD Trucks",
  "JR2": "Isuzu Oasis made by Honda",
  "JSK": "Kawasaki KLX125/KLX125L motorcycle made by Suzuki",
  "JST": "Suzuki Across SUV made by Toyota",
  "JT7": "Toyota bus/van",
  "JTB": "Toyota bus",
  "JTF": "Toyota van/truck",
  "JTG": "Toyota MPV/bus",
  "JTP": "Toyota SUV",
  "JY3": "Yamaha 3-wheel ATV",
  "JY4": "Yamaha 4-wheel ATV",
  "JYA": "Yamaha motorcycles",
  "JYE": "Yamaha snowmobile",
  "KF3": "Merkavim (Israel)",
  "KF6": "Automotive Industries, Ltd. (Israel)",
  "KL3": "GM Daewoo/GM Korea (Holden)",
  "KL4": "GM Korea (Buick)",
  "KL6": "GM Daewoo (GMC)",
  "KL8": "GM Daewoo/GM Korea (Chevrolet car from Changwon plant (Spark))",
  "KLP": "CT&T United (battery electric low-speed vehicles)",
  "KLT": "Tata Daewoo",
  "KLU": "Tata Daewoo",
  "KLY": "Daewoo/GM Daewoo/GM Korea (Chevrolet) from Changwon plant",
  "KMC": "Hyundai commercial truck",
  "KME": "Hyundai commercial truck (semi-tractor)",
  "KMT": "Genesis Motor car",
  "KMU": "Genesis Motor SUV",
  "KMX": "Hyundai Galloper SUV",
  "KN1": "Asia Motors",
  "KN2": "Asia Motors",
  "KNF": "Kia, special vehicles",
  "KNG": "Kia minibus/bus",
  "KNL": "Kia Elan/Vigato made by Kia Motech",
  "KPB": "SsangYong car",
  "KPD": "SsangYong TransStar (bus)",
  "L0N": "Ezytrail (camper trailers)",
  "L10": "Geely Emgrand",
  "L1K": "Chongqing Hengtong Bus",
  "L1N": "XPeng Motors",
  "L2B": "Jiangsu Baodiao Locomotive Co., Ltd. (motorcycles)",
  "L2C": "Chery Jaguar Land Rover",
  "L37": "Huzhou Daixi Zhenhua Technology Trade Co., Ltd. (motorcycles)",
  "L3H": "Shanxi Victory Automobile Manufacturing",
  "L4F": "Suzhou Eagle Electric Vehicle Manufacturing",
  "L4H": "Ningbo Longjia Motorcycle",
  "L4S": "Zhejiang Xingyue Vehicle Co Ltd. (motorcycles)",
  "L4Y": "Qingqi Group Ningbo Rhon Motorcycle / Ningbo Dalong Smooth Locomotive Industry",
  "L5E": "Zoomlion Heavy Industry Science & Technology",
  "L66": "Zhuhai Granton Bus and Coach",
  "L6F": "Shandong Liangzi Power",
  "L6J": "Zhejiang Kayo Motor Co. Ltd. (ATV)",
  "L6K": "Shanghai Howhit Machinery Manufacture",
  "L82": "Baotian",
  "L8A": "Jinhua Youngman Automobile Manufacturing",
  "L8Y": "Zhejiang Jonway Motorcycle Manufacturing",
  "L9G": "Zhuhai Guangtong Automobile Co., Ltd. (bus)",
  "L9N": "Zhejiang Taotao Vehicles",
  "LA6": "Xiamen King Long United Automotive Industry Co., Ltd. (bus)",
  "LA7": "Radar Auto (Geely)",
  "LA8": "Anhui Ankai",
  "LAA": "Shanghai Jialing Vehicle Co., Ltd. (motorcycle)",
  "LAE": "Jinan Qingqi Motorcycle",
  "LAL": "Sundiro Honda Motorcycle",
  "LAP": "Zhuzhou Nanfang Motorcycle",
  "LAT": "Luoyang Northern Ek Chor Motorcycle Co., Ltd. (Dayang)",
  "LB1": "Fujian Benz",
  "LB3": "Zhejiang Geely Holding Group (Geely, Galaxy, Geometry, Kandi)",
  "LB4": "Chongqing Yinxiang Motorcycle Group",
  "LB5": "Foshan City Fosti Motorcycle",
  "LB7": "Tibet New Summit Motorcycle",
  "LBV": "BMW Brilliance (BMW, Zinoro)",
  "LBX": "Jiangsu Kinroad Xintian Motorcycle Manufacture Co. Ltd. (motorcycles)",
  "LBZ": "Yantai Shuchi Vehicle Co., Ltd. (bus)",
  "LC0": "BYD Auto (BYD, Denza)",
  "LC2": "Changzhou Kwang Yang Motor Co., Ltd. (Kymco)",
  "LC6": "Changzhou Haojue Suzuki Motorcycle",
  "LCR": "Gonow",
  "LD3": "Guangdong Tayo Motorcycle Technology Co. (Zontes) (motorcycle)",
  "LD5": "Benzhou Vehicle Industry Group Ltd. (motorcycle)",
  "LDB": "Dadi Auto",
  "LDF": "Dezhou Fulu Vehicle Co., Ltd. (motorcycles), BAW Yuanbao electric car (Ace P1 in Norway)",
  "LDK": "FAW Bus (Dalian)",
  "LDP": "Dongfeng, Dongfeng Fengshen (Aeolus), Voyah, Renault City K-ZE/Venucia e30 made by eGT New",
  "LE8": "Guangzhou Panyu Hua'Nan Motors Industry Co. Ltd. (motorcycles)",
  "LEC": "Tianjin Qingyuan Electric Vehicle",
  "LEF": "Jiangling Motors Corporation Ltd. (JMC)",
  "LEH": "Zhejiang Riya Motorcycle",
  "LEW": "Dongfeng commercial vehicle",
  "LF3": "Lifan Motorcycle",
  "LFA": "Ford Lio Ho Motor Co Ltd. old designation (Taiwan)",
  "LFF": "Zhejiang Taizhou Wangye Power",
  "LFJ": "Fujian Motors Group (Keyton)",
  "LFM": "FAW Toyota Motor (Toyota, Ranz)",
  "LFN": "FAW Bus (Wuxi) Co., Ltd. (truck, bus)",
  "LFU": "Lifeng Group Co., Ltd. (motorcycles)",
  "LFX": "Sany Heavy Industry (truck)",
  "LFZ": "Leapmotor",
  "LG6": "Dayun Group",
  "LGA": "Dongfeng Commercial Vehicle Co., Ltd. trucks",
  "LGC": "Dongfeng Commercial Vehicle Co., Ltd. bus chassis",
  "LGD": "Dongfeng Commercial Vehicle",
  "LGF": "Dongfeng Commercial Vehicle Co., Ltd. bus chassis",
  "LGG": "Dongfeng Liuzhou Motor (Forthing/Fengxing)",
  "LGJ": "Dongfeng Fengshen (Aeolus)",
  "LGL": "Guilin Daewoo",
  "LGV": "Heshan Guoji Nanlian Motorcycle Industry",
  "LGW": "Great Wall Motor (GWM, Haval, Ora, Tank, Wey)",
  "LGZ": "Guangzhou Denway Bus",
  "LH0": "WM Motor Technology Co., Ltd. (Weltmeister)",
  "LHA": "Shuanghuan Auto",
  "LHG": "GAC Honda (Honda, Everus, Acura)",
  "LHJ": "Chongqing Astronautic Bashan Motorcycle Manufacturing",
  "LHM": "Dongfeng Renault Automobile Co",
  "LHW": "CRRC Electric Vehicle Co., Ltd. (bus)",
  "LJ4": "Shanghai Jmstar Motorcycle",
  "LJ5": "Cixi Kingring Motorcycle Co., Ltd. (Jinlun)",
  "LJ8": "Zotye Auto made by Jiangnan Automobile",
  "LJD": "Yueda Kia (previously Dongfeng Yueda Kia) (Kia, Horki) & Human Horizons - HiPhi (made unde",
  "LJM": "Sunlong (bus)",
  "LJN": "Zhengzhou Nissan",
  "LJR": "CIMC Vehicles Group (truck trailer)",
  "LJS": "Yaxing Coach, Asiastar Bus",
  "LJU": "Lotus Technology (Wuhan Lotus Cars Co., Ltd.)",
  "LJV": "Sinotruk Chengdu Wangpai Commercial Vehicle",
  "LJW": "JMC Landwind",
  "LJX": "JMC Ford",
  "LK2": "Anhui JAC Bus",
  "LK6": "SAIC-GM-Wuling (Wuling, Baojun) microcars and other vehicles",
  "LK8": "Zhejiang Yule New Energy Automobile Technology Co., Ltd. (ATV)",
  "LKC": "BAIC commercial vehicles, previously Changhe",
  "LKG": "Youngman Lotus Automobile",
  "LKH": "Hafei Motor",
  "LKT": "Yunnan Lifan Junma Vehicle Co., Ltd. commercial vehicles",
  "LL0": "Sanmen County Yongfu Machine Co., Ltd. (motorcycles)",
  "LL2": "WM Motor Technology Co., Ltd. (Weltmeister)",
  "LL3": "Xiamen Golden Dragon Bus",
  "LLC": "Loncin Motor Co., Ltd. (motorcycle)",
  "LLJ": "Jiangsu Xinling Motorcycle Fabricate",
  "LLN": "Qoros",
  "LLP": "Zhejiang Jiajue Motorcycle Manufacturing",
  "LLU": "Dongfeng Fengxing Jingyi",
  "LLV": "Lifan, Maple (owned by Geely), Livan Automotive",
  "LLX": "Yudo Auto",
  "LM0": "Wangye Holdings Co., Ltd. (motorcycles)",
  "LM6": "SWM (automobiles)",
  "LM8": "Seres (formerly SF Motors), AITO",
  "LME": "Skyworth (formerly Skywell), Elaris Beo",
  "LMF": "Jiangmen Zhongyu Motor",
  "LMG": "GAC Motor, Trumpchi, Dodge Attitude made by GAC",
  "LMH": "Jiangsu Guowei Motor Co., Ltd. (Motoleader)",
  "LMP": "Geely Sichuan Commercial Vehicle",
  "LMV": "XPeng Motors G3 (not G3i) made by Haima",
  "LMW": "GAC Group, Dodge Journey made by GAC",
  "LMX": "Forthing (Dongfeng Fengxing)",
  "LNA": "GAC Aion New Energy Automobile Co., Ltd., Hycan",
  "LNB": "BAIC Motor (Senova, Weiwang, Huansu) & Arcfox & Xiaomi SU7 built by BAIC",
  "LND": "JMEV (Jiangxi Jiangling Group New Energy Vehicle Co., Ltd.), Eveasy/Mobilize Limo",
  "LNE": "Zhejiang CRRC Electric Vehicle Co., Ltd. (bus)",
  "LNN": "Chery Automobile, Omoda, Jaecoo",
  "LNP": "NAC MG UK Limited & Nanjing Fiat Automobile",
  "LNV": "Naveco (Nanjing Iveco Automobile Co. Ltd.)",
  "LNX": "Dongfeng Liuzhou Motor (Chenglong trucks)",
  "LNY": "Yuejin",
  "LP6": "Guangzhou Panyu Haojian Motorcycle Industry",
  "LPA": "Changan PSA (DS Automobiles)",
  "LPE": "BYD Auto",
  "LPS": "Polestar",
  "LR4": "Yadi Technology Group",
  "LR6": "Guangzhou Dayun Vehicle",
  "LRB": "SAIC-General Motors (Buick for export)",
  "LRD": "Beijing Foton Daimler Automotive Co., Ltd. Auman trucks",
  "LRE": "SAIC-General Motors (Cadillac for export)",
  "LRP": "Chongqing Rato Power Co. Ltd. (Asus)",
  "LRR": "Ningbo Longjia Power Technology Co., Ltd. (motorcycles)",
  "LRW": "Tesla, Inc. (Gigafactory Shanghai)",
  "LS3": "Hejia New Energy Vehicle",
  "LS4": "Changan Automobile (MPV/SUV)",
  "LS5": "Changan Automobile (car) & Changan Suzuki",
  "LS6": "Changan Automobile & Deepal Automobile & Avatr",
  "LS7": "JMC Heavy Duty Truck",
  "LS8": "Henan Shaolin Auto Co., Ltd. (bus)",
  "LSC": "Changan Automobile (light truck)",
  "LSF": "SAIC Maxus or LDV pickup/SUV & Chevrolet S10 Max & Shanghai Sunwin Bus Corporation",
  "LSH": "SAIC Maxus van or LDV van & Chevrolet Express Max",
  "LSK": "SAIC Maxus or LDV van",
  "LT1": "Yangzhou Tonghua Semi-Trailer Co., Ltd. (truck trailer)",
  "LTA": "ZX Auto",
  "LTN": "Soueast-built Chrysler & Dodge vehicles",
  "LTP": "National Electric Vehicle Sweden AB (NEVS)",
  "LTW": "Zhejiang Dianka Automobile Technology Co. Ltd. (Enovate)",
  "LUD": "Dongfeng Nissan Diesel Motor",
  "LUG": "Qiantu Motor",
  "LUJ": "Zhejiang Shanqi Tianying Vehicle Industry Co., Ltd. (motorcycles)",
  "LUR": "Chery Automobile, iCar",
  "LUX": "Dongfeng Yulon Motor",
  "LUZ": "Hozon Auto New Energy Automobile Co., Ltd. (Neta)",
  "LV3": "Hengchi Automobile (Evergrande Group)",
  "LV7": "Jinan Qingqi Motorcycle",
  "LVA": "Foton Motor",
  "LVB": "Foton Motor truck",
  "LVC": "Foton Motor bus",
  "LVF": "Changhe Suzuki",
  "LVG": "GAC Toyota (Toyota, Leahead)",
  "LVH": "Dongfeng Honda (Honda, Ciimo)",
  "LVM": "Chery Commercial Vehicle",
  "LVP": "Dongfeng Sokon Motor Company (DFSK)",
  "LVR": "Changan Mazda",
  "LVT": "Chery Automobile, Exeed, Jetour, Soueast",
  "LVU": "Chery Automobile, Jetour",
  "LVX": "Aiways Automobiles Company Ltd",
  "LW4": "Li Auto",
  "LWB": "Wuyang Honda Motorcycle (Guangzhou)",
  "LWE": "Yangtse Motor Group (bus)",
  "LWG": "Chongqing Huansong Industries (Group)",
  "LWL": "Qingling Isuzu",
  "LWM": "Chongqing Wonjan Motorcycle",
  "LWX": "Shanghai Wanxiang Automobile Manufacturing Co., Ltd. (bus)",
  "LX6": "Jiangmen City Huari Group Co. Ltd. (motorcycle)",
  "LX8": "Chongqing Xgjao (Xinganjue) Motorcycle",
  "LXA": "Jiangmen Qipai Motorcycle",
  "LXD": "Ningbo Dongfang Lingyun Vehicle Made Co., Ltd. (motorcycle)",
  "LXG": "Xuzhou Construction Machinery Group Co., Ltd. (XCMG)",
  "LXK": "Shanghai Meitian Motorcycle",
  "LXM": "Xiamen Xiashing Motorcycle Co., Ltd. (SYM)",
  "LXN": "Link Tour",
  "LXV": "Beijing Borgward Automotive",
  "LXW": "JMC - Ford",
  "LXY": "Chongqing Shineray Motorcycle",
  "LY4": "Chongqing Yingang Science & Technology Group Co., Ltd. (motorcycle)",
  "LYB": "Weichai (Yangzhou) Yaxing Automobile",
  "LYD": "Taizhou City Kaitong Motorcycle Co., Ltd. (motorcycle)",
  "LYJ": "Beijing ZhongdaYanjing Auto Co., Ltd. (bus)",
  "LYM": "Zhuzhou Jianshe Yamaha Motorcycle",
  "LYS": "Nanjing Vmoto Manufacturing Co. Ltd. (motorcycle)",
  "LYU": "Huansu (BAIC Motor & Yinxiang Group)",
  "LYV": "Volvo Cars Chengdu factory & Luqiao factory",
  "LZ0": "Shandong Wuzheng Group",
  "LZ4": "Jiangsu Linzhi Shangyang Group",
  "LZF": "SAIC Iveco Hongyan (-2021), SAIC Hongyan (2021-)",
  "LZK": "Sinotruk (CNHTC) Huanghe bus",
  "LZL": "Zengcheng Haili Motorcycle Ltd",
  "LZS": "Zongshen, Electra Meccanica Vehicles Corp. (Solo) made by Zongshen",
  "LZU": "Guangzhou Isuzu Bus",
  "LZW": "SAIC-GM-Wuling (Wuling, Baojun, Chevrolet [for export])",
  "M3G": "Isuzu Motors India",
  "M6F": "UM Lohia Two Wheelers Private Limited",
  "MA8": "Daewoo Motor India",
  "MAA": "India Kawasaki Motors Pvt. Ltd",
  "MAH": "Fiat India Automobiles Pvt. Ltd",
  "MAN": "Eicher Polaris Multix",
  "MB2": "Hyundai Motor India (SUV)",
  "MB7": "Reva Electric Car Company/Mahindra Reva Electric Vehicles Pvt. Ltd",
  "MB8": "Suzuki Motorcycle India Limited",
  "MBF": "Royal Enfield",
  "MBK": "MAN Trucks India Pvt. Ltd",
  "MBL": "Hero MotoCorp",
  "MBU": "Swaraj Vehicles Limited",
  "MBV": "Premier Automobiles Ltd",
  "MBX": "Piaggio India (Piaggio Ape)",
  "MBY": "Asia Motor Works Ltd",
  "MC1": "Force Motors Ltd",
  "MC4": "Dilip Chhabria Design Pvt Ltd",
  "MCD": "Mahindra Two Wheelers",
  "MCG": "Atul Auto Ltd",
  "MCL": "International Cars And Motors Ltd",
  "MD6": "TVS Motor Company",
  "MD7": "LML Ltd including Genuine Scooter Company Stella",
  "MD9": "Shuttle Cars India",
  "MDE": "Kinetic Engineering Limited",
  "MDT": "Kerala Automobiles Limited",
  "ME1": "India Yamaha Motor Pvt. Ltd",
  "ME3": "Royal Enfield",
  "ME4": "Honda Motorcycle and Scooter India",
  "MEC": "Daimler India Commercial Vehicles (BharatBenz)",
  "MEG": "Harley-Davidson India",
  "MER": "Benelli India",
  "MES": "Mahindra Navistar",
  "MET": "Piaggio India (Vespa, Indian-market Aprilia)",
  "MF3": "PT Hyundai Motor Manufacturing Indonesia",
  "MH1": "PT Astra Honda Motor (motorcycle)",
  "MH3": "PT Yamaha Indonesia Motor Mfg",
  "MH4": "PT Kawasaki Motor Indonesia",
  "MH8": "PT Suzuki Indomobil Motor (motorcycle)",
  "MHB": "PT Nissan Motor Indonesia",
  "MHD": "PT Indomobil Suzuki International",
  "MHK": "PT Astra Daihatsu Motor (includes Toyotas made by Astra Daihatsu)",
  "MHL": "PT Mercedes-Benz Indonesia",
  "MHY": "PT Suzuki Indomobil Motor (car, MPV, van)",
  "MJB": "GM Indonesia",
  "MK2": "PT Mitsubishi Motors Krama Yudha Indonesia",
  "MK3": "PT SGMW Motor Indonesia (Wuling)",
  "MKF": "PT Sokonindo Automobile (DFSK)",
  "ML0": "Ducati Motor (Thailand)",
  "ML5": "Kawasaki Motors Enterprise Co. Ltd. (Thailand)",
  "MLB": "Siam Yamaha",
  "MLE": "Thai Yamaha Motor",
  "MLW": "Sco Motor Co., Ltd. (motorcycle)",
  "MLY": "Harley-Davidson Thailand",
  "MMA": "Mitsubishi Motors (Thailand)",
  "MMD": "Mitsubishi Motors (Thailand)",
  "MME": "Mitsubishi Motors (Thailand)",
  "MMF": "BMW Manufacturing (Thailand)",
  "MML": "MG Thailand (SAIC-CP)",
  "MMR": "Subaru/Tan Chong Subaru Automotive (Thailand)",
  "MMU": "Holden Thailand (Colorado RG, Colorado 7, & Trailblazer)",
  "MN3": "Eagle Vista [Canada] made by Mitsubishi (Thailand)",
  "MNA": "Ford Thailand (Ford-Mazda AutoAlliance Thailand plant) for Australia/New Zealand export",
  "MNC": "Ford Thailand (Ford-Mazda AutoAlliance Thailand plant) for left-hand drive markets",
  "MNK": "Hino Motors Manufacturing Thailand",
  "MNU": "Great Wall Motor Manufacturing (Thailand)",
  "MP2": "Mazda BT-50 pickup built by Isuzu Motors (Thailand)",
  "MP3": "Plymouth Colt 100 [Canada] made by Mitsubishi (Thailand)",
  "MP5": "Foton Motor Thailand",
  "MPB": "Ford Thailand (Ford Thailand Manufacturing plant)",
  "MR1": "Toyota Thailand",
  "MR2": "Toyota Thailand (Gateway plant) (passenger cars & CUVs)",
  "MR3": "Toyota Thailand (Hilux Champ chassis cab)",
  "MRT": "Neta (Hozon Auto) made by Bangchan General Assembly",
  "MS0": "Super Seven Stars Motors Myanmar",
  "MS1": "Super Seven Stars Automotive Myanmar",
  "MS3": "Suzuki Myanmar Motor",
  "MX3": "Hyundai Trans Auto (Kazakhstan)",
  "MXB": "Saryarka AvtoProm bus (Kazakhstan)",
  "MXL": "Yutong bus made by Qaz Tehna (Kazakhstan)",
  "MXV": "IMZ-Ural Ural Motorcycles (Kazakhstan)",
  "MYH": "Ather Energy",
  "MZ7": "MG Motor India Pvt. Ltd",
  "MZB": "Kia India Pvt. Ltd",
  "MZD": "Classic Legends Private Limited – Jawa",
  "MZZ": "Citroen India (PCA Automobiles India Private Limited)",
  "NAA": "Iran Khodro (Peugeot Iran)",
  "NAC": "Mammut (truck trailers)",
  "NAD": "Škoda",
  "NAL": "Maral Sanat Jarvid (truck trailers)",
  "NAP": "Pars Khodro",
  "NAS": "SAIPA",
  "NC0": "Oghab Afshan (bus)",
  "NFB": "Honda Atlas Cars Pakistan Ltd",
  "NG3": "Lucky Motor Corporation",
  "NL1": "TOGG",
  "NL2": "HABAS/HBS (bus)",
  "NLC": "Askam Kamyon Imalat Ve Ticaret A.S",
  "NLF": "Koluman Otomotiv Endustri A.S. (truck trailer)",
  "NLJ": "Hyundai Assan Otomotiv van",
  "NLN": "Karsan",
  "NLR": "Otokar",
  "NLT": "Temsa",
  "NLZ": "Tezeller",
  "NM1": "Oyak Renault Otomobil Fabrikaları A.Ş",
  "NMA": "MAN Türkiye A.Ş",
  "NMB": "Mercedes-Benz Türk A.S. Buses",
  "NMC": "BMC Otomotiv Sanayi ve Ticaret A.Ş",
  "NMH": "Honda Anadolu motorcycle",
  "NMS": "Otoyol San. A.Ş",
  "NNA": "Anadolu Isuzu",
  "NNN": "Gépébus Oréos 4X (based on Otokar Vectio)",
  "NNY": "Yeksan (truck trailer)",
  "NP8": "ÖZGÜL TREYLER (truck trailer)",
  "NPM": "Seyit Usta Treyler (truck trailer)",
  "NPR": "Oztreyler (truck trailer)",
  "NPS": "Nursan (truck trailer)",
  "NRE": "Bozankaya",
  "NRX": "Musoshi",
  "NRY": "Pilotcar Otomotiv",
  "NS2": "JV MAN Auto - Uzbekistan",
  "NSA": "SamAvto / SAZ (Uzbekistan)",
  "NVA": "Khazar (IKCO Dena made in Azerbaijan)",
  "PAB": "Isuzu Philippines Corporation",
  "PAD": "Honda Cars Philippines",
  "PFD": "Hyundai Motor Group Innovation Center in Singapore (HMGICS)",
  "PL8": "Inokom-Hyundai",
  "PLP": "Subaru/Tan Chong Motor Assemblies, Malaysia",
  "PLZ": "Isuzu Malaysia",
  "PM1": "BMW & Mini/Inokom",
  "PM2": "Perodua",
  "PMA": "MAN Truck & Bus Malaysia",
  "PMH": "Honda Malaysia (car)",
  "PMK": "Honda Boon Siew (motorcycle)",
  "PML": "Hicom",
  "PMN": "Modenas",
  "PMS": "Suzuki Assemblers Malaysia (motorcycle)",
  "PMV": "Hong Leong Yamaha Motor Sdn. Bhd",
  "PMY": "Hong Leong Yamaha Motor Sdn. Bhd",
  "PN1": "UMW Toyota Motor",
  "PN2": "UMW Toyota Motor",
  "PN8": "Nissan/Tan Chong Motor Assemblies, Malaysia",
  "PNS": "TMSBUS Malaysia (bus)",
  "PNV": "Volvo Car Manufacturing Malaysia",
  "PP1": "Mazda/Inokom",
  "PP3": "Hyundai/Inokom",
  "PPP": "Suzuki",
  "PPV": "Volkswagen/HICOM Automotive Manufacturers (Malaysia)",
  "PR8": "Ford",
  "PRA": "Sinotruk",
  "PRH": "Chery (by Chery Alado Holdings [joint venture] at Oriental Assemblers plant)",
  "PRN": "GAC Trumpchi made by Warisan Tan Chong Automotif Malaysia",
  "PRX": "Kia/Inokom",
  "PV3": "Ford made by RMA Automotive Cambodia",
  "R10": "ZAP (HK)",
  "R1J": "Jiayuan Power (Hong Kong) Ltd. (Electric Low-Speed Vehicles) (Hong Kong)",
  "R1N": "Niu Technologies Group Ltd. (Hong Kong)",
  "R2P": "Evoke Electric Motorcycles (Hong Kong)",
  "R36": "HK Shansu Technology Co., Ltd. (Hong Kong)",
  "R3M": "Mangosteen Technology Co., Ltd. (Hong Kong)",
  "R4N": "Elyx Smart Technology Holdings (Hong Kong) Ltd",
  "R82": "Hangzhou Lantu Technology Co., Ltd. (Hong Kong)",
  "RA1": "Steyr Trucks International FZE, UAE",
  "RF5": "Yulon Motor Co. Ltd., Taiwan (Luxgen)",
  "RF8": "EVT Technology Co., Ltd (motorcycle)",
  "RFC": "Taiwan Golden Bee",
  "RFD": "Tai Ling Motor Co Ltd. new designation (Taiwan)",
  "RFV": "Motive Power Industry Co., Ltd. (PGO Scooters including Genuine Scooter Company models mad",
  "RGS": "Kawasaki made by Kymco (Taiwan)",
  "RHA": "Ford Lio Ho Motor Co Ltd. new designation (Taiwan)",
  "RK3": "Honda Taiwan",
  "RK7": "Kawasaki ATV made by Tai Ling Motor Co Ltd (rebadged Suzuki ATV) new designation (Taiwan)",
  "RKJ": "Prince Motors Taiwan",
  "RKL": "Kuozui Motors (Toyota) (Taiwan)",
  "RKM": "China Motor Corporation (Taiwan)",
  "RKR": "Yamaha Motor Taiwan Co. Ltd. new designation",
  "RKT": "Access Motor Co., Ltd. (Taiwan)",
  "RL0": "Ford Vietnam",
  "RL4": "Toyota Motor Vietnam",
  "RLA": "Vina Star Motors Corp. – Mitsubishi (Vietnam)",
  "RLC": "Yamaha Motor Vietnam",
  "RLE": "Isuzu Vietnam Co",
  "RLH": "Honda Vietnam",
  "RLL": "VinFast SUV",
  "RLM": "Mercedes-Benz Vietnam",
  "RLN": "VinFast",
  "RLV": "Vietnam Precision Industrial CO., Ltd. (Can-Am DS 70 & DS 90)",
  "RP8": "Piaggio Vietnam",
  "RUN": "Sollets-Auto ST6 (Russia)",
  "SA3": "Ginetta Cars",
  "SAA": "Austin",
  "SAB": "Optare (1985-2020), Switch Mobility (2021-)",
  "SAD": "Jaguar SUV (E-Pace, F-Pace, I-Pace)",
  "SAF": "ERF trucks",
  "SAH": "Honda made by Austin Rover Group",
  "SAM": "Morris",
  "SAY": "Norton Motorcycles",
  "SAZ": "Freight Rover",
  "SBB": "Leyland Vehicles",
  "SBC": "Iveco Ford Truck",
  "SBF": "Nugent (trailer)",
  "SBJ": "Leyland Bus",
  "SBL": "Leyland Motors & Leyland DAF",
  "SBS": "Scammell",
  "SBU": "United Trailers (truck trailer)",
  "SBV": "Kenworth & Peterbilt trucks made by Leyland Trucks",
  "SBW": "Weightlifter Bodies (truck trailer)",
  "SC5": "Wrightbus (from ~2020)",
  "SC6": "INEOS Automotive SUV",
  "SCD": "Reliant Motors",
  "SCG": "Triumph Engineering Co. Ltd. (original Triumph Motorcycle company)",
  "SCK": "Ifor Williams Trailers",
  "SCM": "Manitowoc Cranes - Grove",
  "SCR": "London Electric Vehicle Company & London Taxi Company & London Taxis International",
  "SCV": "Volvo Truck & Bus Scotland",
  "SD7": "Aston Martin SUV",
  "SD8": "Moke International Ltd",
  "SDC": "SDC Trailers Ltd. (truck trailer)",
  "SDF": "Dodge Trucks – UK 1981–1984",
  "SDG": "Renault Trucks Industries 1985–1992",
  "SDK": "Caterham Cars",
  "SDL": "TVR",
  "SDP": "NAC MG UK & MG Motor UK Ltd",
  "SDU": "Utility (truck trailer)",
  "SEG": "Dennis Eagle Ltd., including Renault Trucks Access and D Access",
  "SEP": "Don-Bur (truck trailer)",
  "SFE": "Alexander Dennis UK",
  "SFN": "Foden Trucks",
  "SFR": "Fruehauf (truck trailer)",
  "SFZ": "Tesla Roadster made by Lotus",
  "SG4": "Coachman (caravans)",
  "SGA": "Avondale (caravans)",
  "SGB": "Bailey (caravans)",
  "SGD": "Swift Group Ltd. (caravans)",
  "SGE": "Elddis (caravans)",
  "SGL": "Lunar Caravans Ltd",
  "SH7": "INEOS Automotive truck",
  "SJ1": "Ree Automotive",
  "SJA": "Bentley SUV",
  "SJB": "Brian James Trailers Ltd",
  "SJK": "Nissan Motor Manufacturing UK - Infiniti",
  "SKA": "Vauxhall",
  "SKB": "Kel-Berg Trailers & Trucks",
  "SKL": "Anaig (UK) Technology Ltd",
  "SLA": "Rolls Royce SUV",
  "SLC": "Thwaites Dumpers",
  "SLG": "McMurtry Automotive",
  "SLN": "Niftylift",
  "SLV": "Volvo bus",
  "SMR": "Montracon (truck trailer)",
  "SMW": "Cartwright (truck trailer)",
  "SMX": "Gray & Adams (truck trailer)",
  "SNE": "Wartburg (East Germany)",
  "SNT": "Trabant (East Germany)",
  "SNZ": "MZ (motorcycle) (Germany)",
  "SPE": "B-ON GmbH (Germany)",
  "ST3": "Calabrese (truck trailer)",
  "SUA": "Autosan (bus)",
  "SUB": "Tramp Trail (trailer)",
  "SUC": "Wiola (trailer)",
  "SUD": "Wielton (truck trailers)",
  "SUG": "Mega Trailers (truck trailer) (Poland)",
  "SUJ": "Jelcz (Poland)",
  "SUM": "Novatrail (truck trailers)",
  "SVH": "ZASŁAW (truck trailer)",
  "SVM": "Inter Cars (truck trailer)",
  "SVS": "BODEX (truck trailer)",
  "SWH": "Temared (trailers)",
  "SWR": "Weekend Trailers (trailers)",
  "SWV": "TA-NO (Poland)",
  "SWZ": "Zremb (trailers)",
  "SX7": "Arthur Bus",
  "SXE": "Neptun Trailers",
  "SXK": "Konar (truck trailer)",
  "SXM": "MELEX Sp. z o.o",
  "SXX": "Martz (trailer)",
  "SXY": "Wecon (truck trailer)",
  "SY1": "Neso Bus (PAK-PCE Polski Autobus Wodorowy)",
  "SYB": "Rydwan (trailer)",
  "SYG": "Gniotpol, GT Trailers Sp. z o. o. (truck trailer)",
  "SZA": "Scania Poland",
  "SZC": "Vectrix (motorcycle)",
  "SZL": "Boro Trailers",
  "SZN": "Przyczepy Głowacz (trailer)",
  "SZR": "Niewiadów (trailer)",
  "T3C": "Lohr Backa Topola (truck trailer) (Serbia)",
  "T7A": "Ebusco (Netherlands)",
  "TAW": "NAW Nutzfahrzeuggesellschaft Arbon & Wetzikon AG (Switzerland)",
  "TBS": "Boschung AG (Switzerland)",
  "TEB": "Bucher Municipal AG (includes Johnston Sweepers) (Switzerland)",
  "TEM": "Twike (SwissLEM AG) (Switzerland)",
  "TFH": "FHS Frech-Hoch AG (truck trailer) (Switzerland)",
  "TJ5": "Vezeko (trailer) (Czech Republic)",
  "TKP": "Panav a.s. (truck trailer) (Czech Republic)",
  "TKX": "Agados s.r.o. (trailer) (Czech Republic)",
  "TKY": "Metaco (truck trailer) (Czech Republic)",
  "TLJ": "Jawa Moto (Czech Republic)",
  "TMC": "Hyundai Motor Manufacturing Czech (SUV)",
  "TNA": "Avia/Daewoo Avia",
  "TNG": "LIAZ (Liberecké Automobilové Závody)",
  "TNT": "Tatra trucks",
  "TNU": "Tatra trucks",
  "TRC": "Csepel bus",
  "TRE": "Rákos bus",
  "TRK": "Credo bus/Kravtex (Hungary)",
  "TRR": "Rába Bus (Hungary)",
  "TSB": "Ikarus Bus",
  "TSC": "VIN assigned by the National Transport Authority of Hungary",
  "TSF": "Alfabusz (Hungary)",
  "TSY": "Keeway Motorcycles (Hungary)",
  "TW0": "CaetanoBus (Portugal)",
  "TW2": "Ford Lusitana (Portugal)",
  "TW4": "UMM (Portugal)",
  "TW6": "Citroën (Portugal)",
  "TW7": "Mini Moke made by British Leyland & Austin Rover Portugal",
  "TWG": "CaetanoBus (Portugal)",
  "TX5": "Mini Moke made by Cagiva (Moke Automobili)",
  "U1A": "Sanos (North Macedonia)",
  "U1V": "VDL Van Hool Macedonia (North Macedonia)",
  "U6A": "Granus (bus) (Slovakia)",
  "UA1": "AUSA Center (Spain)",
  "UA2": "Iveco Massif & Campagnola made by Santana Motors in Spain",
  "UA4": "Irizar e-mobility (Spain)",
  "UCY": "Silence Urban Ecomobility (Spain)",
  "UD3": "Granalu truck trailers (Belgium)",
  "UH2": "De Forenede Trailerfabrikke (trailer) (Denmark)",
  "UHE": "Scanvogn (trailer) (Denmark)",
  "UHL": "Camp-let (recreational vehicle) (Denmark)",
  "UJG": "Garia ApS - Club Car (Denmark)",
  "UKR": "Hero Camper (Denmark)",
  "UMT": "MTDK a/s (truck trailer) (Denmark)",
  "UN1": "Ford Ireland",
  "UU2": "Oltcit",
  "UU4": "Roman/Grivbuz",
  "UU5": "Rocar",
  "UU7": "Euro Bus Diamond",
  "UU9": "Astra Bus",
  "UVW": "UMM (truck trailer)",
  "UWR": "Robus Reșița",
  "UZT": "UTB (Uzina de Tractoare Brașov)",
  "V1Y": "FAS Sanos bus (Yugoslavia/North Macedonia)",
  "V2X": "Ikarbus a.d. (Serbia)",
  "V31": "Tvornica Autobusa Zagreb (TAZ) (Croatia)",
  "V34": "Crobus bus (Croatia)",
  "V61": "Respo Trailers (Estonia)",
  "V6A": "Bestnet AS; Tiki trailers (Estonia)",
  "V6B": "Brentex-Trailer (Estonia)",
  "V6T": "Verge Motorcycles (Estonia)",
  "VA0": "ÖAF, Gräf & Stift",
  "VA4": "KSR Group (motorcycle)",
  "VAH": "Hangler (truck trailer)",
  "VAK": "Kässbohrer Transport Technik",
  "VAV": "Schwarzmüller",
  "VAX": "Schwingenschlogel (truck trailer)",
  "VBF": "Fit-Zel (trailer)",
  "VCF": "Fisker Inc. (Fisker Ocean) made by Magna Steyr",
  "VF5": "Iveco Unic",
  "VFA": "Alpine, Renault Alpine GTA",
  "VFG": "Caravelair (caravans)",
  "VFK": "Fruehauf (truck trailers)",
  "VFN": "Trailor, General Trailers (truck trailers)",
  "VG7": "Renault Trucks",
  "VG8": "Renault Trucks",
  "VGA": "Peugeot Motocycles",
  "VGT": "ASCA (truck trailers)",
  "VGU": "Trouillet (truck trailers)",
  "VGW": "BSLT (truck trailers)",
  "VGX": "Coder (truck trailers)",
  "VGY": "Lohr (truck trailers)",
  "VH1": "Benalu SAS (truck trailer)",
  "VH8": "Microcar",
  "VHR": "Robuste (truck trailer)",
  "VHX": "Manitowoc Cranes - Potain",
  "VJ1": "Heuliez Bus",
  "VJ2": "Mia Electric",
  "VJ4": "Gruau",
  "VJR": "Ligier",
  "VJY": "Gruau",
  "VK1": "SEG (truck trailer)",
  "VK2": "Grandin Automobiles",
  "VK8": "Venturi Automobiles",
  "VKD": "Cheval Liberté (horse trailer)",
  "VL4": "Bluecar, Citroen E-Mehari",
  "VLG": "Aixam-Mega",
  "VM3": "Chereau (truck trailer)",
  "VMK": "Renault Sport Spider",
  "VMS": "Automobiles Chatenet",
  "VMT": "SECMA",
  "VMW": "Gépébus Oréos 55",
  "VN4": "Voxan",
  "VP3": "G. Magyar (truck trailers)",
  "VPL": "Nosmoke S.A.S",
  "VR1": "DS Automobiles",
  "VR3": "Peugeot (under Stellantis)",
  "VR7": "Citroën (under Stellantis)",
  "VRW": "Goupil",
  "VS1": "Pegaso",
  "VS5": "Renault Spain",
  "VS7": "Citroën Spain",
  "VS8": "Peugeot Spain",
  "VSC": "Talbot",
  "VSF": "Santana Motors (Anibal/PS-10, 300/350)",
  "VSR": "Leciñena (truck trailers)",
  "VSY": "Renault V.I. Spain (bus)",
  "VTD": "Montesa Honda (Honda Montesa motorcycle models)",
  "VTL": "Yamaha Spain (motorcycles)",
  "VTP": "Rieju S.A. (motorcycles)",
  "VTR": "Gas Gas",
  "VV1": "Lecitrailer Group (truck trailers)",
  "VV5": "Prim-Ball (truck trailers)",
  "VVC": "SOR Ibérica (truck trailers)",
  "VVG": "Tisvol (truck trailers)",
  "VWF": "Guillén Group (truck trailers)",
  "VWL": "Indox (truck trailers)",
  "VXE": "Opel Automobile Gmbh/Vauxhall van",
  "VXF": "Fiat van (Fiat Scudo, Ulysse '22-)",
  "VXK": "Opel Automobile Gmbh/Vauxhall car/SUV",
  "VXY": "Neobus a.d. (Serbia)",
  "VYC": "Lancia Ypsilon (4th gen.)",
  "VYE": "Jeep Compass (3rd gen. - EU market '26-)",
  "VYF": "Fiat Doblo '23- & Fiat Topolino '23- & Fiat Grande Panda '25-",
  "VYJ": "Ram 1200 '25- (sold in Mexico)",
  "VYS": "Renault & Alpine made by Ampere (Renault 5 E-Tech, Renault 4 E-Tech, Alpine A290)",
  "VZ2": "Avtomontaža (bus) (Slovenia)",
  "W04": "Buick Regal & Buick Cascada",
  "W08": "Saturn Astra",
  "W0D": "Obermaier (truck trailer)",
  "W0V": "Opel Automobile Gmbh/Vauxhall & Holden (since 2017)",
  "W1A": "smart",
  "W1H": "Freightliner Econic",
  "W1N": "Mercedes-Benz SUV",
  "W1T": "Mercedes-Benz truck",
  "W1V": "Mercedes-Benz van",
  "W1W": "Mercedes-Benz MPV (van with 2 or 3 rows of seats) (North America)",
  "W1X": "Mercedes-Benz incomplete vehicle (North America)",
  "W1Y": "Mercedes-Benz truck (cargo van with 1 row of seats) (North America)",
  "W1Z": "Mercedes-Benz bus (van with more than 3 rows of seats) (North America)",
  "W2W": "Freightliner Sprinter MPV (van with 2 or 3 rows of seats)",
  "W2X": "Freightliner Sprinter incomplete vehicle",
  "W2Y": "Freightliner Sprinter truck (cargo van with 1 row of seats)",
  "W2Z": "Freightliner Sprinter bus (van with more than 3 rows of seats)",
  "WAC": "Audi/Porsche RS2 Avant",
  "WAF": "Ackermann (truck trailer)",
  "WB0": "Böckmann Fahrzeugwerke GmbH (trailers)",
  "WB2": "Blyss (trailer)",
  "WB3": "BMW Motorrad Motorcycles made in India by TVS",
  "WB4": "BMW Motorrad Motorscooters made in China by Loncin",
  "WB5": "BMW i SUV",
  "WBC": "Boom Trikes",
  "WBJ": "Bitter Cars",
  "WBK": "Böcker Maschinenwerke GmbH",
  "WBL": "Blumhardt (truck trailers)",
  "WBU": "Bürstner (caravans)",
  "WCD": "Freightliner Sprinter bus (van with more than 3 rows of seats) 2008–2019",
  "WCM": "Wilcox (truck trailer)",
  "WD6": "Freightliner Unimog truck",
  "WD7": "Freightliner Unimog incomplete vehicle",
  "WDR": "Freightliner Sprinter MPV (van with 2 or 3 rows of seats) 2005–2019",
  "WDT": "Dethleffs (caravans)",
  "WDW": "Dodge Sprinter bus (van with more than 3 rows of seats) 2008–2009",
  "WEG": "Ablinger (trailer)",
  "WEL": "e.GO Mobile AG",
  "WFB": "Feldbinder Spezialfahrzeugwerke GmbH",
  "WFC": "Fendt (caravans)",
  "WFD": "Fliegl Trailer",
  "WFN": "Tadano Faun GmbH",
  "WG0": "Goldhofer AG (truck trailer)",
  "WGB": "Göppel Bus GmbH",
  "WH7": "Hüfferman (truck trailer)",
  "WHB": "Hobby (recreational vehicles)",
  "WHD": "Humbaur GmbH (truck trailer)",
  "WHL": "Hulco (trailer)",
  "WHW": "Hako GmbH",
  "WHY": "Hymer (recreational vehicles)",
  "WK0": "Kögel (truck trailers)",
  "WKE": "Krone (truck trailers)",
  "WKN": "Knaus, Weinsberg (caravans)",
  "WKV": "Kässbohrer Fahrzeugwerke Gmbh (truck trailers)",
  "WLA": "Langendorf semi-trailers",
  "WLF": "Liebherr (mobile crane)",
  "WMG": "Demag Cranes",
  "WMM": "Karl Müller GmbH & Co. KG (truck trailers)",
  "WMP": "M & V GmbH (truck trailers)",
  "WMU": "Hako GmbH (Multicar)",
  "WMZ": "MINI SUV",
  "WNA": "Next.e.GO Mobile SE",
  "WRA": "Renders (truck trailers)",
  "WRJ": "Riese & Müller (bicycle)",
  "WS5": "StreetScooter",
  "WS7": "Sono Motors",
  "WSE": "STEMA Metalleichtbau GmbH (trailers)",
  "WSJ": "STERK Trailers (truck trailers)",
  "WSK": "Schmitz-Cargobull Gotha (truck trailers)",
  "WSM": "Schmitz-Cargobull (truck trailers)",
  "WSP": "Spitzer (truck trailers)",
  "WSV": "Aebi Schmidt Group",
  "WTA": "Tabbert (caravans)",
  "WU1": "Audi Sport GmbH (formerly quattro GmbH) SUV",
  "WV4": "Volkswagen Commercial Vehicles (2nd gen. Amarok & T7 Transporter made by Ford)",
  "WV5": "Volkswagen Commercial Vehicles (T7 Caravelle made by Ford)",
  "WVM": "Arbeitsgemeinschaft VW-MAN",
  "WVP": "Viseon Bus",
  "WWA": "Wachenhut (truck trailer)",
  "WWC": "WM Meyer (truck trailer)",
  "WZ1": "Toyota Supra (Fifth generation for North America)",
  "X0T": "Tonar (truck trailer)",
  "X1D": "RAF (Rīgas Autobusu Fabrika)",
  "X1E": "KAvZ (Russia)",
  "X1F": "NefAZ (Russia)",
  "X1M": "PAZ (Russia)",
  "X1P": "Ural (Russia)",
  "X21": "Diesel-S (truck trailer) (Russia)",
  "X2L": "Fox Trailer (truck trailer) (Russia)",
  "X4K": "Volgabus (Volzhanin) (Russia)",
  "X4T": "Sommer (truck trailer) (Russia)",
  "X5A": "UralSpetzTrans (trailer) (Russia)",
  "X6D": "VIS-AVTO (Russia)",
  "X6S": "TZA (truck trailer) (Russia)",
  "X8J": "IMZ-Ural Ural Motorcycles",
  "X8U": "Scania Russia",
  "X90": "GRAZ (truck trailer)",
  "X96": "GAZ",
  "X9F": "Ford Motor Company ZAO",
  "X9L": "GM-AvtoVAZ",
  "X9N": "Samoltor (minibus)",
  "X9P": "Volvo Vostok ZAO Volvo Trucks",
  "X9W": "Brilliance, Lifan made by Derways",
  "X9X": "Great Wall Motors",
  "XD2": "CTTM Cargoline (truck trailer) (Russia)",
  "XDN": "Mercedes Sprinter Classic made by GAZ (Russia)",
  "XE2": "AMKAR Automaster (truck trailer) (Russia)",
  "XEA": "AmberAvto (Avtotor) (Russia)",
  "XG3": "Petros Petropoulos Group - Ecoshift NOOS electric motorscooters (Greece)",
  "XG4": "Mpitis (trailer) (Greece)",
  "XG5": "Stavropoulos trailers (Greece)",
  "XG6": "MGK Hellenic Motor motorcycles (Greece)",
  "XG8": "Gorgolis SA motorcycles (Greece)",
  "XJ4": "PKTS (PK Transportnye Sistemy) bus (Russia)",
  "XJY": "Bonum (truck trailer) (Russia)",
  "XKM": "Volgabus (Russia)",
  "XL3": "Ebusco",
  "XL4": "Lightyear",
  "XLA": "DAF Bus International",
  "XLC": "Ford Netherlands",
  "XLD": "Pacton Trailers B.V",
  "XLH": "Hapert (trailer)",
  "XLJ": "Anssems (trailer)",
  "XLK": "Burg Trailer Service BV (truck trailer)",
  "XLU": "Henra (trailer)",
  "XLV": "DAF Bus",
  "XLW": "Terberg Benschop BV",
  "XM4": "RAVO Holding B.V. (sweeper)",
  "XMD": "NedCar B.V. Mitsubishi Motors (RHD)",
  "XMG": "VDL Bus International",
  "XMR": "Nooteboom Trailers",
  "XN1": "Kraker Trailers Axel B.V. (truck trailer)",
  "XNB": "NedCar B.V. Mitsubishi Motors made by Pininfarina (Colt CZC convertible - RHD)",
  "XNJ": "Broshuis (truck trailer)",
  "XNL": "VDL Bus & Coach",
  "XNT": "Pacton Trailers B.V. (truck trailer)",
  "XP7": "Tesla Europe (based in the Netherlands) (Gigafactory Berlin-Brandenburg)",
  "XPN": "Knapen Trailers",
  "XPP": "Atec Trailers",
  "XR7": "Qarry",
  "XRP": "Proline (trailer)",
  "XRY": "D-TEC (truck trailer)",
  "XTB": "Moskvitch / AZLK (Russia)",
  "XTC": "KAMAZ (Russia)",
  "XTD": "LuAZ (Ukraine)",
  "XTE": "ZAZ (Ukraine)",
  "XTF": "GolAZ (Russia)",
  "XTH": "GAZ (Russia)",
  "XTJ": "Lada Oka made by SeAZ (Russia)",
  "XTK": "IzhAvto (Russia)",
  "XTM": "MAZ (Belarus); used until 1997",
  "XTP": "Ural (Russia)",
  "XTS": "ChMZAP (truck trailer)",
  "XTU": "Trolza, previously ZiU (Russia)",
  "XTW": "LAZ (Ukraine)",
  "XTY": "LiAZ (Russia)",
  "XTZ": "ZiL (Russia)",
  "XU6": "Avtodom (minibus) (Russia)",
  "XUS": "Nizhegorodets (minibus) (Russia)",
  "XUV": "Avtotor (DFSK, SWM)",
  "XUZ": "InterPipeVAN (truck trailer)",
  "XVG": "MARZ (bus) (Russia)",
  "XVU": "Start (truck trailer)",
  "XW7": "Toyota Motor Manufacturing Russia",
  "XWF": "Avtotor (Russia, Chevrolet Tahoe/Opel/Cadillac/Hummer SKD)",
  "XX3": "Ujet Manufacturing (Luxembourg)",
  "XZB": "SIMAZ (bus) (Russia)",
  "XZE": "Specpricep (truck trailer)",
  "XZG": "Great Wall Motor (Haval Motor Rus)",
  "XZP": "Gut Trailer (truck trailer)",
  "XZT": "FoxBus (minibus) (Russia)",
  "Y3D": "MTM (truck trailer) (Belarus)",
  "Y3F": "Lida Buses Neman (Belarus)",
  "Y3J": "Belkommunmash (Belarus)",
  "Y3K": "Neman Bus (Belarus)",
  "Y3M": "MAZ (Belarus)",
  "Y3W": "VFV built by Unison (Belarus)",
  "Y4F": "Ford Belarus",
  "Y4K": "Geely / BelGee (Belarus)",
  "Y6B": "Iveco (Ukraine)",
  "Y6E": "LAZ (Ukraine)",
  "Y6J": "Bogdan group (Ukraine)",
  "Y6L": "Bogdan group including buses, Hyundai made by Bogdan (Ukraine)",
  "Y6U": "Škoda Auto made by Eurocar (Ukraine)",
  "Y6W": "PGFM (trailer) (Ukraine)",
  "Y6Y": "LEV (trailer) (Ukraine)",
  "Y7A": "KrAZ trucks (Ukraine)",
  "Y7B": "Bogdan group (Ukraine)",
  "Y7C": "Great Wall Motors, Geely made by KrASZ (Ukraine)",
  "Y7D": "GAZ made by KrymAvtoGAZ (Ukraine)",
  "Y7F": "Boryspil Bus Factory (BAZ) (Ukraine)",
  "Y7S": "Korida-Tech (trailer) (Ukraine)",
  "Y7W": "Geely made by KrASZ (Ukraine)",
  "Y7X": "ChRZ - Ruta (minibus) (Ukraine)",
  "Y8A": "LAZ (Ukraine)",
  "Y8H": "UNV Leader (trailer) (Ukraine)",
  "Y8S": "Alekseevka Ximmash (truck trailer)",
  "Y8X": "GAZ Gazelle made by KrASZ (Ukraine)",
  "Y9A": "PAVAM (trailer) (Ukraine)",
  "Y9H": "LAZ (Ukraine)",
  "Y9M": "AMS (trailer) (Ukraine)",
  "Y9T": "Dnipro (trailer) (Ukraine)",
  "Y9W": "Pragmatec (trailer) (Ukraine)",
  "Y9Z": "Lada, Renault made in Ukraine",
  "YA2": "Atlas Copco Group",
  "YA5": "Renders (truck trailers)",
  "YAF": "Faymonville (special transport trailers)",
  "YAG": "Syma aanhangwagenbouw BV (trailers)",
  "YAM": "MAX Trailer (truck trailers)",
  "YAR": "Toyota Motor Europe (based in Belgium) used for Toyota ProAce, Toyota ProAce City and Toyo",
  "YB1": "Volvo Trucks Belgium (truck)",
  "YB2": "Volvo Trucks Belgium (bus chassis)",
  "YB4": "LAG Trailers N.V. (truck trailer)",
  "YB6": "Jonckheere (VDL Belgium)",
  "YBC": "Toyota Supra (Fifth generation for Europe)",
  "YBD": "Addax Motors",
  "YC3": "Eduard Trailers",
  "YD3": "Chateau Caravans (Belgium)",
  "YE1": "Van Hool (trailers) (Belgium)",
  "YE6": "STAS (truck trailer)",
  "YE7": "Turbo's Hoet (truck trailer)",
  "YF1": "Närko (truck trailer) (Finland)",
  "YF3": "NTM (truck trailer) (Finland)",
  "YGU": "JJ-Trailer (trailer) (Finland)",
  "YH1": "Solifer (caravans)",
  "YH2": "BRP Finland (Lynx snowmobiles)",
  "YH4": "Fisker Automotive (Fisker Karma) built by Valmet Automotive",
  "YS5": "OmniNova (minibus)",
  "YS7": "Solifer (recreational vehicles)",
  "YSC": "Cadillac BLS (made by Saab)",
  "YSM": "Polestar cars",
  "YSP": "Volta Trucks AB",
  "YSR": "Polestar SUV",
  "YT7": "Kabe (recreational vehicles)",
  "YU1": "Fogelsta, Brenderup Group (trailer)",
  "YVV": "WiMa 442 EV",
  "YYB": "Tysse (trailer) (Norway)",
  "YYC": "Think Nordic (Norway)",
  "Z07": "Volgabus (Russia)",
  "Z6F": "Ford Sollers (Russia)",
  "Z76": "SEMAZ (Kazakhstan)",
  "Z7C": "Luidor (bus) (Russia)",
  "Z7N": "KAvZ (bus) (Russia)",
  "Z7T": "RoAZ (bus) (Russia)",
  "Z7X": "Isuzu Rus (Russia)",
  "Z8N": "Nissan Manufacturing Rus (Russia)",
  "Z8T": "PCMA Rus (Peugeot, Citroen, Mitsubishi) (Russia)",
  "Z8Y": "Nasteviya (bus) (Russia)",
  "Z94": "Hyundai Motor Manufacturing Rus (2008-2023), Solaris Auto - AGR Automotive (2023-) (Russia",
  "Z9B": "KuzbassAvto (Hyundai bus) (Russia)",
  "Z9M": "Mercedes-Benz Trucks Vostok (Russia)",
  "Z9N": "Samotlor-NN (Iveco) (Russia)",
  "ZA0": "Acerbi (truck trailer)",
  "ZA4": "Omar (truck trailer)",
  "ZAH": "Rolfo SpA (car transporter)",
  "ZAJ": "Trigano SpA; Roller Team recreational vehicles",
  "ZAS": "Alfa Romeo SUV 2018-",
  "ZAX": "Zorzi (truck trailer)",
  "ZB3": "Cardi (truck trailer)",
  "ZBA": "Piacenza (truck trailer)",
  "ZBB": "Bertone",
  "ZBD": "InBus",
  "ZBW": "Rayton-Fissore Magnum",
  "ZC1": "AnsaldoBreda S.p.A",
  "ZCB": "E. Bartoletti SpA (truck trailer)",
  "ZCM": "BredaMenarinibus / Menarinibus / IIA (Industria Italiana Autobus)",
  "ZCN": "Astra Veicoli Industriali S.p.A",
  "ZCV": "Vibreti (truck trailer)",
  "ZCZ": "BredaBus",
  "ZD5": "Casalini",
  "ZDJ": "ACM Biagini",
  "ZDT": "De Tomaso Modena SpA",
  "ZDY": "Cacciamali",
  "ZE5": "Carmosino (truck trailer)",
  "ZEB": "Ellebi (trailer)",
  "ZEH": "Trigano SpA (former SEA Group); McLouis & Mobilvetta recreational vehicles",
  "ZES": "Bimota",
  "ZEX": "TM Racing (motorcycle)",
  "ZF4": "Qvale",
  "ZFE": "KL Motorcycle",
  "ZFJ": "Carrozzeria Pezzaioli (truck trailer)",
  "ZFM": "Fantic Motor",
  "ZFR": "Pininfarina",
  "ZG2": "FAAM (commercial vehicle)",
  "ZGP": "Merker (truck trailer)",
  "ZH5": "FB Mondial (motorcycle)",
  "ZHU": "Husqvarna Motorcycles Under Cagiva ownership",
  "ZHZ": "Menci SpA (truck trailer)",
  "ZJT": "Italjet",
  "ZKC": "Ducati Energia Free Duck (electric quadricycle)",
  "ZLF": "Tazzari GL SpA",
  "ZLM": "Moto Morini srl",
  "ZLV": "Laverda",
  "ZN0": "SWM Motorcycles S.r.l",
  "ZN3": "Iveco Defence",
  "ZN6": "Maserati SUV",
  "ZNN": "Energica",
  "ZP6": "XEV",
  "ZP8": "Regis Motors",
  "ZPB": "Lamborghini SUV",
  "ZPY": "DR Automobiles",
  "ZR1": "Microlino",
  "ZRG": "Tazzari GL Imola SpA",
  "ZSG": "Ferrari SUV",
  "ZX1": "TAM (Tovarna Avtomobilov Maribor) bus (Slovenia)",
  "ZY1": "Adria (recreational vehicles) (Slovenia)",
  "ZZ1": "Tomos motorcycle (Slovenia)",
};

export function lookupUniversalWmi(vin: string): string | null {
  if (!vin || vin.length < 3) return null;
  return UNIVERSAL_WMI_MAP[vin.slice(0, 3).toUpperCase()] ?? null;
}

/**
 * Country/region hint derived from VIN positions 1-2 per ISO 3779.
 * Not exact (one WMI prefix can cover multiple countries within a region),
 * but correct at the continent level and frequently at the country level.
 */
export function countryFromVin(vin: string): string | null {
  if (!vin || vin.length < 2) return null;
  const c1 = vin.charAt(0).toUpperCase();
  const c2 = vin.charAt(1).toUpperCase();
  // North America
  if (c1 === "1" || c1 === "4" || c1 === "5") return "United States";
  if (c1 === "2") return "Canada";
  if (c1 === "3") {
    if (c2 >= "A" && c2 <= "W") return "Mexico";
    return "North America";
  }
  // Asia
  if (c1 === "J") return "Japan";
  if (c1 === "K") {
    if (c2 >= "L" && c2 <= "R") return "Korea";
    return "Asia";
  }
  if (c1 === "L") return "China";
  if (c1 === "M") {
    if (c2 >= "A" && c2 <= "E") return "India";
    if (c2 >= "F" && c2 <= "K") return "Indonesia";
    if (c2 >= "L" && c2 <= "R") return "Thailand";
    return "Asia";
  }
  if (c1 === "N") {
    if (c2 >= "F" && c2 <= "K") return "Pakistan";
    if (c2 >= "L" && c2 <= "R") return "Turkey";
    return "Middle East / Asia";
  }
  if (c1 === "P") {
    if (c2 >= "A" && c2 <= "E") return "Philippines";
    if (c2 >= "L" && c2 <= "R") return "Malaysia";
    return "Asia";
  }
  if (c1 === "R") {
    if (c2 >= "F" && c2 <= "K") return "Taiwan";
    if (c2 >= "L" && c2 <= "R") return "Vietnam";
    return "Asia / Oceania";
  }
  // Europe
  if (c1 === "S") {
    if (c2 >= "A" && c2 <= "M") return "United Kingdom";
    if (c2 >= "N" && c2 <= "T") return "Germany (East / former)";
    if (c2 >= "U" && c2 <= "Z") return "Poland";
    return "Europe";
  }
  if (c1 === "T") {
    if (c2 >= "A" && c2 <= "H") return "Switzerland";
    if (c2 >= "J" && c2 <= "P") return "Czech Republic";
    if (c2 >= "R" && c2 <= "V") return "Hungary";
    if (c2 >= "W" && c2 <= "Z") return "Portugal";
    return "Europe";
  }
  if (c1 === "V") {
    if (c2 >= "A" && c2 <= "E") return "Austria";
    if (c2 >= "F" && c2 <= "R") return "France";
    if (c2 >= "S" && c2 <= "W") return "Spain";
    return "Europe";
  }
  if (c1 === "W") return "Germany";
  if (c1 === "X") {
    if (c2 >= "A" && c2 <= "E") return "Bulgaria";
    if (c2 >= "F" && c2 <= "K") return "Greece";
    if (c2 >= "L" && c2 <= "R") return "Netherlands";
    if (c2 >= "S" && c2 <= "W") return "Russia";
    return "Europe";
  }
  if (c1 === "Y") {
    if (c2 >= "A" && c2 <= "E") return "Belgium";
    if (c2 >= "F" && c2 <= "K") return "Finland";
    if (c2 >= "S" && c2 <= "W") return "Sweden";
    return "Northern Europe";
  }
  if (c1 === "Z") {
    if (c2 >= "A" && c2 <= "R") return "Italy";
    return "Europe";
  }
  // Africa
  if (c1 >= "A" && c1 <= "H") return "Africa";
  // Oceania / South America
  if (c1 === "6") return "Australia";
  if (c1 === "7") return "New Zealand";
  if (c1 === "8") return "South America";
  if (c1 === "9") return "Brazil";
  return null;
}
